// Rust-specific templates for the `scaffold` subcommand's generated crate:
// `Cargo.toml`, `bindings/rust/build.rs`, `bindings/rust/lib.rs`,
// `examples/walk.rs`, and `.gitignore`. Everything here is plain string
// rendering — no `Grammar` DOM involved — parameterized only by the crate's
// name, header preference, and (for `bindings/rust/visitor.rs`) the
// already-rendered visitor source.
//
// `name`, as received from `super::render_scaffold`, is the raw name the
// user typed (or the filename stem) — possibly hyphenated. `render` below
// normalizes it once into `identifier_name` and passes that to every
// template except `cargo_toml`, which alone keeps the raw form: Cargo's
// own package-naming convention keeps hyphens (`ts-bnf-tool`,
// `tree-sitter-bnf`, this workspace's own crates), while everything else
// here — the `extern "C"` symbol, the `c_config.compile(...)` target, the
// module path `examples/*.rs` `use`s — needs a strict Rust/C identifier
// (#378).

use std::path::PathBuf;

use indoc::formatdoc;

use crate::util::hyphens_to_underscores;

use super::ScaffoldFile;

/// Renders every file this target's generated crate needs, at the paths a
/// Rust crate expects them: `Cargo.toml`/`bindings/rust/lib.rs`/
/// `examples/walk.rs`/`.gitignore` are left alone on rerun (tutorial- or
/// user-editable), the rest are always regenerated.
pub(super) fn render(
    name: &str,
    no_header: bool,
    visitor_source: String,
    ast_data: Option<(String, String)>,
) -> Vec<ScaffoldFile> {
    let identifier_name = hyphens_to_underscores(name);
    let mut files = vec![
        ScaffoldFile {
            path: PathBuf::from("Cargo.toml"),
            content: cargo_toml(name),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/build.rs"),
            content: build_rs(&identifier_name, no_header),
            preserve_existing: false,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/lib.rs"),
            content: lib_rs(&identifier_name, no_header, ast_data.is_some()),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/visitor.rs"),
            content: visitor_source,
            preserve_existing: false,
        },
        ScaffoldFile {
            path: PathBuf::from("examples/walk.rs"),
            content: walk_example(&identifier_name),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from(".gitignore"),
            content: "/target\n".to_string(),
            // Not grammar-derived — a hardcoded constant that never changes
            // as the grammar evolves — and the tutorial-editable files
            // above already establish the pattern for content like this:
            // written once, then left for the user to extend (#376).
            preserve_existing: true,
        },
    ];
    if let Some((ast_file, root_rule)) = ast_data {
        files.push(ScaffoldFile {
            path: PathBuf::from("bindings/rust/ast.rs"),
            content: ast_file,
            preserve_existing: false,
        });
        files.push(ScaffoldFile {
            path: PathBuf::from("examples/ast.rs"),
            content: ast_example(&identifier_name, &root_rule),
            preserve_existing: true,
        })
    }

    files
}

/// Renders the generated crate's `Cargo.toml`.
///
/// Pinned to `edition = "2021"`, same as `tree-sitter-bnf`'s own
/// hand-written `Cargo.toml`: [`lib_rs`] emits a bare
/// `extern "C" { ... }` block (again mirroring `tree-sitter-bnf`'s own
/// `bindings/rust/lib.rs`), which is a hard error under edition 2024
/// (requires `unsafe extern "C"` there instead). Bumping this file's
/// edition without also updating that block breaks generation.
fn cargo_toml(name: &str) -> String {
    formatdoc! {r#"
        [package]
        name = "{name}"
        description = "Rust library for parsing and traversing {name} source, generated by ts-bnf-tool"
        version = "0.1.0"
        # Pinned: bindings/rust/lib.rs's `extern "C" {{ ... }}` block requires
        # `unsafe extern "C"` under edition 2024; bump both together, or not at all.
        edition = "2021"
        license = "MIT"

        build = "bindings/rust/build.rs"
        include = [
          "bindings/rust/*",
          "examples/*",
          "grammar.js",
          "queries/*",
          "src/*",
          "tree-sitter.json",
        ]

        [lib]
        path = "bindings/rust/lib.rs"

        [dependencies]
        tree-sitter-language = "0.1"
        tree-sitter = "0.26.8"

        [build-dependencies]
        cc = "1.2"

        [workspace]
    "#}
}

/// Renders the generated crate's `bindings/rust/build.rs` — compiles
/// `src/parser.c` (and `src/scanner.c`, if present) into the crate, same as
/// `tree-sitter-bnf`'s own build script.
///
/// Always regenerated on rerun (`preserve_existing: false` in [`render`]),
/// unlike `Cargo.toml`/`lib.rs`/`examples/walk.rs`/`.gitignore` — so, like
/// `visitor.rs`, it carries the generated-file header warning against
/// hand-edits (#376).
fn build_rs(name: &str, no_header: bool) -> String {
    let header = if no_header {
        String::new()
    } else {
        let version = env!("CARGO_PKG_VERSION");
        format!("// Generated by ts-bnf-tool v{version} \u{2014} do not edit by hand.\n\n")
    };
    formatdoc! {r#"
        {header}fn main() {{
            let src_dir = std::path::Path::new("src");

            let mut c_config = cc::Build::new();
            c_config.std("c11").include(src_dir);

            #[cfg(target_env = "msvc")]
            c_config.flag("-utf-8");

            let parser_path = src_dir.join("parser.c");
            c_config.file(&parser_path);
            println!("cargo:rerun-if-changed={{}}", parser_path.to_str().unwrap());

            let scanner_path = src_dir.join("scanner.c");
            if scanner_path.exists() {{
                c_config.file(&scanner_path);
                println!("cargo:rerun-if-changed={{}}", scanner_path.to_str().unwrap());
            }}

            c_config.compile("{name}");
        }}
    "#}
}

/// Renders the generated crate's `bindings/rust/lib.rs`: the `LANGUAGE`/
/// `NODE_TYPES` parser bindings (same shape as `tree-sitter generate`'s own
/// per-language output, e.g. `tree-sitter-bnf/bindings/rust/lib.rs`), a
/// `pub mod visitor;` for the generated `Visitor` trait, and a `parse`
/// convenience function wrapping parser setup.
///
/// Only ever scaffolded once (`preserve_existing: true` in [`render`]):
/// unlike `visitor.rs`, this file's `LANGUAGE`/`NODE_TYPES`/`parse` content
/// never needs to change on a grammar edit, and it's exactly where the
/// tutorial invites users to add `pub mod` declarations for their own
/// hand-written `Visitor` implementations.
fn lib_rs(name: &str, no_header: bool, has_ast: bool) -> String {
    let header = if no_header {
        String::new()
    } else {
        let version = env!("CARGO_PKG_VERSION");
        format!(
            "// Generated by ts-bnf-tool v{version} from {name}.bnf \u{2014} do not edit by hand.\n\n"
        )
    };
    let ast_mod = if has_ast { "pub mod ast;\n" } else { "" };
    formatdoc! {r#"
        {header}//! This crate provides `{name}` language support for the [tree-sitter][]
        //! parsing library, plus a generated [`Visitor`][visitor::Visitor] trait for
        //! traversing the parsed tree. See [`parse`] for a minimal end-to-end example,
        //! or `examples/walk.rs` for a runnable one.
        //!
        //! [tree-sitter]: https://tree-sitter.github.io/

        use tree_sitter_language::LanguageFn;

        pub mod visitor;
        {ast_mod}// Add `pub mod` declarations here for your own Visitor implementations.

        extern "C" {{
            fn tree_sitter_{name}() -> *const ();
        }}

        /// The tree-sitter [`LanguageFn`] for this grammar.
        pub const LANGUAGE: LanguageFn = unsafe {{ LanguageFn::from_raw(tree_sitter_{name}) }};

        /// The content of this grammar's `node-types.json` file.
        pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

        /// Parses `source` with this grammar's tree-sitter parser.
        ///
        /// # Errors
        ///
        /// Returns an error if the language fails to load (should never happen for a
        /// language compiled into this crate) or if parsing does not produce a tree.
        pub fn parse(source: &str) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {{
            let mut parser = tree_sitter::Parser::new();
            parser.set_language(&LANGUAGE.into())?;
            parser
                .parse(source, None)
                .ok_or_else(|| "tree-sitter failed to parse the given source".into())
        }}
    "#}
}

/// Renders `examples/ast.rs`: parses a file and builds one typed root node
/// via the grammar's generated `TryFrom<SourceNode<'tree>>` impl, then
/// pretty-prints it with `{:#?}` — every generated struct/enum derives
/// `Debug`, so this recurses through the whole typed tree with no
/// per-kind code, proving the generated AST types actually compile and
/// work, the same bar `walk.rs` is already held to.
fn ast_example(name: &str, root_rule: &str) -> String {
    formatdoc! {r#"
        //! Parses a file with the `{name}` parser and builds a typed root node
        //! using the generated AST types. Run it with:
        //!
        //! ```sh
        //! cargo run --example ast -- <file>
        //! ```

        use {name}::visitor::SourceNode;
        use {name}::ast::{root_rule};

        fn main() {{
            let path = std::env::args()
                .nth(1)
                .expect("usage: cargo run --example ast -- <file>");
            let source =
                std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {{path}}: {{e}}"));

            let tree = {name}::parse(&source).expect("parse must succeed");

            let root: {root_rule} = SourceNode {{ node: tree.root_node(), source: &source }}
                .try_into()
                .expect("root node must build successfully");
            println!("{{path}}:\n{{root:#?}}");
        }}
    "#}
}

/// Renders `examples/walk.rs`: a `Counter` visitor that counts every named
/// node by overriding only [`Visitor::combine`] — the one method the trait
/// doesn't give a default for — proving the crate works without writing any
/// per-kind override.
fn walk_example(name: &str) -> String {
    formatdoc! {r#"
        //! Parses a file with the `{name}` parser and prints how many named
        //! nodes it contains, using nothing but the generated `Visitor` trait's
        //! required `combine` method. Run it with:
        //!
        //! ```sh
        //! cargo run --example walk -- <file>
        //! ```

        use {name}::visitor::{{SourceNode, Visitor}};

        /// Counts every node visited, leaves and non-leaves alike: `combine` runs
        /// exactly once per visited node, regardless of kind.
        struct Counter {{
            total: usize,
        }}

        impl<'t> Visitor<'t> for Counter {{
            type Output = ();
            type Error = std::convert::Infallible;

            fn combine(&mut self, _results: Vec<()>) -> Result<(), Self::Error> {{
                self.total += 1;
                Ok(())
            }}
        }}

        fn main() {{
            let path = std::env::args()
                .nth(1)
                .expect("usage: cargo run --example walk -- <file>");
            let source =
                std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {{path}}: {{e}}"));

            let tree = {name}::parse(&source).expect("parse must succeed");

            let mut counter = Counter {{ total: 0 }};
            counter
                .visit(SourceNode {{ node: tree.root_node(), source: &source }})
                .expect("Infallible visitor must not fail");

            println!("{{path}}: {{}} node(s)", counter.total);
        }}
    "#}
}
