// Rust-specific templates for the `scaffold` subcommand's generated crate:
// `Cargo.toml`, `bindings/rust/build.rs`, `bindings/rust/lib.rs`,
// `examples/walk.rs`, and `.gitignore`. Everything here is plain string
// rendering — no `Grammar` DOM involved — parameterized only by the crate's
// name, header preference, and (for `bindings/rust/visitor.rs`) the
// already-rendered visitor source.

use std::path::PathBuf;

use indoc::formatdoc;

use super::ScaffoldFile;

/// Renders every file this target's generated crate needs, at the paths a
/// Rust crate expects them: `Cargo.toml`/`bindings/rust/lib.rs`/
/// `examples/walk.rs` are left alone on rerun (tutorial-editable), the rest
/// are always regenerated.
pub(super) fn render(name: &str, no_header: bool, visitor_source: String) -> Vec<ScaffoldFile> {
    vec![
        ScaffoldFile {
            path: PathBuf::from("Cargo.toml"),
            content: cargo_toml(name),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/build.rs"),
            content: build_rs(name),
            preserve_existing: false,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/lib.rs"),
            content: lib_rs(name, no_header),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from("bindings/rust/visitor.rs"),
            content: visitor_source,
            preserve_existing: false,
        },
        ScaffoldFile {
            path: PathBuf::from("examples/walk.rs"),
            content: walk_example(name),
            preserve_existing: true,
        },
        ScaffoldFile {
            path: PathBuf::from(".gitignore"),
            content: "/target\n".to_string(),
            preserve_existing: false,
        },
    ]
}

/// Renders the generated crate's `Cargo.toml`.
///
/// Pinned to `edition = "2021"`, same as `tree-sitter-bnf`'s own
/// hand-written `Cargo.toml`: [`lib_rs`] emits a bare
/// `extern "C" { ... }` block (again mirroring `tree-sitter-bnf`'s own
/// `bindings/rust/lib.rs`), which is a hard error under edition 2024
/// (requires `unsafe extern "C"` there instead). Bumping this file's
/// edition without also updating that block breaks generation.
fn cargo_toml(name: &str) -> String {
    formatdoc! {r#"
        [package]
        name = "{name}"
        description = "Rust library for parsing and traversing {name} source, generated by ts-bnf-tool"
        version = "0.1.0"
        # Pinned: bindings/rust/lib.rs's `extern "C" {{ ... }}` block requires
        # `unsafe extern "C"` under edition 2024; bump both together, or not at all.
        edition = "2021"
        license = "MIT"

        build = "bindings/rust/build.rs"
        include = [
          "bindings/rust/*",
          "grammar.js",
          "queries/*",
          "src/*",
          "tree-sitter.json",
        ]

        [lib]
        path = "bindings/rust/lib.rs"

        [dependencies]
        tree-sitter-language = "0.1"
        tree-sitter = "0.26.8"

        [build-dependencies]
        cc = "1.2"

        [workspace]
    "#}
}

/// Renders the generated crate's `bindings/rust/build.rs` — compiles
/// `src/parser.c` (and `src/scanner.c`, if present) into the crate, same as
/// `tree-sitter-bnf`'s own build script.
fn build_rs(name: &str) -> String {
    formatdoc! {r#"
        fn main() {{
            let src_dir = std::path::Path::new("src");

            let mut c_config = cc::Build::new();
            c_config.std("c11").include(src_dir);

            #[cfg(target_env = "msvc")]
            c_config.flag("-utf-8");

            let parser_path = src_dir.join("parser.c");
            c_config.file(&parser_path);
            println!("cargo:rerun-if-changed={{}}", parser_path.to_str().unwrap());

            let scanner_path = src_dir.join("scanner.c");
            if scanner_path.exists() {{
                c_config.file(&scanner_path);
                println!("cargo:rerun-if-changed={{}}", scanner_path.to_str().unwrap());
            }}

            c_config.compile("{name}");
        }}
    "#}
}

/// Renders the generated crate's `bindings/rust/lib.rs`: the `LANGUAGE`/
/// `NODE_TYPES` parser bindings (same shape as `tree-sitter generate`'s own
/// per-language output, e.g. `tree-sitter-bnf/bindings/rust/lib.rs`), a
/// `pub mod visitor;` for the generated `Visitor` trait, and a `parse`
/// convenience function wrapping parser setup.
///
/// Only ever scaffolded once (`preserve_existing: true` in [`render`]):
/// unlike `visitor.rs`, this file's `LANGUAGE`/`NODE_TYPES`/`parse` content
/// never needs to change on a grammar edit, and it's exactly where the
/// tutorial invites users to add `pub mod` declarations for their own
/// hand-written `Visitor` implementations.
fn lib_rs(name: &str, no_header: bool) -> String {
    let fn_name = name.replace('-', "_");
    let header = if no_header {
        String::new()
    } else {
        let version = env!("CARGO_PKG_VERSION");
        format!(
            "// Generated by ts-bnf-tool v{version} from {name}.bnf \u{2014} do not edit by hand.\n\n"
        )
    };
    formatdoc! {r#"
        {header}//! This crate provides `{name}` language support for the [tree-sitter][]
        //! parsing library, plus a generated [`Visitor`][visitor::Visitor] trait for
        //! traversing the parsed tree. See [`parse`] for a minimal end-to-end example,
        //! or `examples/walk.rs` for a runnable one.
        //!
        //! [tree-sitter]: https://tree-sitter.github.io/

        use tree_sitter_language::LanguageFn;

        pub mod visitor;
        // Add `pub mod` declarations here for your own Visitor implementations.

        extern "C" {{
            fn tree_sitter_{fn_name}() -> *const ();
        }}

        /// The tree-sitter [`LanguageFn`] for this grammar.
        pub const LANGUAGE: LanguageFn = unsafe {{ LanguageFn::from_raw(tree_sitter_{fn_name}) }};

        /// The content of this grammar's `node-types.json` file.
        pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

        /// Parses `source` with this grammar's tree-sitter parser.
        ///
        /// # Errors
        ///
        /// Returns an error if the language fails to load (should never happen for a
        /// language compiled into this crate) or if parsing does not produce a tree.
        pub fn parse(source: &str) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {{
            let mut parser = tree_sitter::Parser::new();
            parser.set_language(&LANGUAGE.into())?;
            parser
                .parse(source, None)
                .ok_or_else(|| "tree-sitter failed to parse the given source".into())
        }}
    "#}
}

/// Renders `examples/walk.rs`: a `Counter` visitor that counts every named
/// node by overriding only [`Visitor::combine`] — the one method the trait
/// doesn't give a default for — proving the crate works without writing any
/// per-kind override.
fn walk_example(name: &str) -> String {
    let crate_name = name.replace('-', "_");
    formatdoc! {r#"
        //! Parses a file with the `{name}` parser and prints how many named
        //! nodes it contains, using nothing but the generated `Visitor` trait's
        //! required `combine` method. Run it with:
        //!
        //! ```sh
        //! cargo run --example walk -- <file>
        //! ```

        use {crate_name}::visitor::{{SourceNode, Visitor}};

        /// Counts every node visited, leaves and non-leaves alike: `combine` runs
        /// exactly once per visited node, regardless of kind.
        struct Counter {{
            total: usize,
        }}

        impl<'t> Visitor<'t> for Counter {{
            type Output = ();
            type Error = std::convert::Infallible;

            fn combine(&mut self, _results: Vec<()>) -> Result<(), Self::Error> {{
                self.total += 1;
                Ok(())
            }}
        }}

        fn main() {{
            let path = std::env::args()
                .nth(1)
                .expect("usage: cargo run --example walk -- <file>");
            let source =
                std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {{path}}: {{e}}"));

            let tree = {crate_name}::parse(&source).expect("parse must succeed");

            let mut counter = Counter {{ total: 0 }};
            counter
                .visit(SourceNode {{ node: tree.root_node(), source: &source }})
                .expect("Infallible visitor must not fail");

            println!("{{path}}: {{}} node(s)", counter.total);
        }}
    "#}
}
