use crate::dom::FieldTargetKinds;
use crate::dom::ast::merge::{MergeConfig, MergeEntry};
use crate::dom::ast::{AstFieldSpec, AstNodeSpec};
use crate::dom::{
    Grammar, ast::derive_ast_node_specs, visitor::text::indent, visitor::to_snake_case,
};
use crate::util::find_first_name_collision;
use indexmap::IndexMap;
use indoc::{formatdoc, indoc};
use std::fmt::{self, Formatter};

/// Renders a [`Grammar`]'s derived AST-struct shape (see [`super`]) as a
/// complete Rust source file: one typed struct/enum plus a
/// `TryFrom<SourceNode<'tree>>` impl per node kind, sharing one
/// `BuildError` across all of them.
///
/// Only buildable via [`RustAst::new`] — see its own doc comment for why.
pub struct RustAst<'a> {
    /// The grammar to derive the AST types from
    grammar: &'a Grammar,
    /// The source filename shown in the generated-file header (`<stdin>` for stdin).
    source: &'a str,
    /// When `true`, suppress the generated-file header comment.
    no_header: bool,
    /// Rust type name registered for each distinct multi-shape target-kind
    /// set, keyed by the sorted kind names — see "Resolved: multi-shape
    /// enum naming" below and [`ShapeName`]. Built once, here, not
    /// recomputed per field.
    multi_shape_names: IndexMap<Vec<String>, ShapeName>,
    /// The validated `--merge-config`, if any. `None` emits every kind's
    /// Stage-A struct as `pub`, under its default derived name, unchanged
    /// from phase 3. `Some` marks any kind claimed by a `merge` entry's
    /// `from` list as non-`pub` (see [`kind_is_merged_away`]), renames a
    /// `passthrough`-claimed kind's struct (see [`kind_display_name`]), and
    /// emits one `pub enum {target}` per `merge` entry ([`fmt_structs`]).
    merge_config: Option<&'a MergeConfig>,
}

impl<'a> RustAst<'a> {
    /// Builds a `RustAst` for `grammar`, computing the multi-shape enum
    /// naming table ([`build_multi_shape_names`]) up front so every
    /// per-kind struct emitted later can look a field's type up rather
    /// than deriving it — see "Resolved: multi-shape enum naming".
    ///
    /// - `source`: the source filename shown in the generated-file header
    ///   (`<stdin>` for stdin).
    /// - `no_header`: when `true`, suppresses the generated-file header
    ///   comment.
    /// - `merge_config`: the validated `--merge-config`, if any — see the
    ///   `merge_config` field's own doc comment.
    pub fn new(
        grammar: &'a Grammar,
        source: &'a str,
        no_header: bool,
        merge_config: Option<&'a MergeConfig>,
    ) -> Result<Self, String> {
        let multi_shape_names = build_multi_shape_names(grammar, merge_config)?;
        Ok(Self {
            grammar,
            source,
            no_header,
            multi_shape_names,
            merge_config,
        })
    }
}

impl RustAst<'_> {
    /// Emits `use super::visitor::SourceNode;` — the first line of real
    /// content in the generated file, right after `fmt_header`'s
    /// comment/blank-line pair — followed by the `Pragma` struct and its
    /// `From<SourceNode<'_>>` impl. `Pragma` stores 1-indexed
    /// `line`/`column` (tree-sitter itself is 0-indexed; this converts
    /// once here).
    fn fmt_pragma(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            use super::visitor::SourceNode;

            /// A node's start position in its source file.
            /// 1-indexed (tree-sitter uses 0-index; this converts once here).
            #[derive(Debug)]
            pub struct Pragma {
                pub line: usize,
                pub column: usize,
            }

            impl From<SourceNode<'_>> for Pragma {
                fn from(node: SourceNode<'_>) -> Self {
                    let point = node.node.start_position();
                    Pragma { line: point.row + 1, column: point.column + 1 }
                }
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Emits the generated-file header comment, unless suppressed by
    /// `no_header` — identical wording to [`super::super::GrammarJs`]'s, since
    /// this is also generated code that shouldn't be hand-edited. Unlike
    /// `GrammarJs::fmt_header`, a blank line follows the comment: the next
    /// thing emitted is a Rust `use` statement, and comment-blank-`use` reads
    /// more naturally than comment-immediately-`use`.
    fn fmt_header(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.no_header {
            let version = env!("CARGO_PKG_VERSION");
            writeln!(
                f,
                "// Generated by ts-bnf-tool v{version} from {} \u{2014} do not edit by hand.",
                self.source
            )?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits a second `impl<'tree> SourceNode<'tree>` block (`visitor.rs`
    /// defines the struct itself; this only adds inherent methods) with
    /// the three helpers every generated `TryFrom` impl needs:
    /// `child_by_field` and `children_by_field` for single-target and
    /// `multiple: true` fields respectively, and `text` for a leaf kind's
    /// own source text.
    fn fmt_node_helpers(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            impl<'tree> SourceNode<'tree> {
                /// The child at `field_name`, if present, bundled with this node's
                /// own source text.
                pub fn child_by_field(&self, field_name: &str) -> Option<SourceNode<'tree>> {
                    self.node
                        .child_by_field_name(field_name)
                        .map(|node| SourceNode { node, source: self.source })
                }
            
                /// Every child at `field_name`, in declaration order, each bundled
                /// with this node's own source text — for `multiple: true` fields
                /// (`Vec<T>`); see the worked example above.
                pub fn children_by_field(&self, field_name: &str) -> Vec<SourceNode<'tree>> {
                    let mut cursor = self.node.walk();
                    self.node
                        .children_by_field_name(field_name, &mut cursor)
                        .map(|node| SourceNode { node, source: self.source })
                        .collect()
                }
            
                /// This node's own source text — for a leaf kind's `text: String` field.
                pub fn text(&self) -> Result<&'tree str, BuildError> {
                    self.node
                        .utf8_text(self.source.as_bytes())
                        .map_err(BuildError::InvalidUtf8)
                }
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Emits `BuildError`, the error type shared by every generated
    /// `TryFrom` impl: a required field absent from a node
    /// (`MissingField`), a multi-shape field's child with a kind outside
    /// its declared set (`UnexpectedKind`), or a leaf node's text not
    /// being valid UTF-8 (`InvalidUtf8`, defensive — shouldn't happen for
    /// a grammar's own tokenizer output).
    fn fmt_build_error(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            /// An error building a typed AST node from a parsed tree.
            #[derive(Debug)]
            pub enum BuildError {
                /// A field the grammar guarantees is present was absent on this
                /// particular node — shouldn't happen for a tree that parsed without
                /// errors, but `child_by_field` returns `Option`, so this is what a
                /// `None` becomes.
                MissingField { kind: &'static str, field: &'static str },
                /// A multi-shape field's child had a kind outside its declared
                /// target-kind set.
                UnexpectedKind { expected: &'static str, found: String },
                /// A leaf node's text was not valid UTF-8 — a grammar's own tokenizer
                /// should only ever produce valid UTF-8 out of valid UTF-8 source, so
                /// this is defensive, not expected in practice.
                InvalidUtf8(std::str::Utf8Error),
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Builds one kind's full declaration + `impl`: resolves the Rust
    /// struct name once — [`kind_display_name`], a `passthrough` entry's
    /// `target` override if one claims `kind`, else `pascal_case(kind)` —
    /// and whether it should be `pub` ([`kind_is_merged_away`]: a kind
    /// claimed by a `merge` entry is emitted private, so nothing outside
    /// the generated crate can construct or name it directly, while
    /// `enum {Target}`'s variant still wraps it and reuses this same
    /// `TryFrom` impl unchanged — see `plans/342.5.md`). Both are passed to
    /// [`fmt_struct_decl`] (using `self.multi_shape_names` to resolve
    /// multi-shape field types) and [`fmt_struct_try_from`], which, unlike
    /// [`fmt_multi_shape_enum`]'s `try_from` half, already returns its own
    /// complete `impl` block at one consistent scale, so no `indent()` step
    /// is needed here.
    fn fmt_struct(&self, kind: &str, spec: &AstNodeSpec) -> String {
        let struct_name = kind_display_name(kind, self.merge_config);
        let is_pub = !kind_is_merged_away(kind, self.merge_config);
        let decl = fmt_struct_decl(
            &struct_name,
            kind,
            spec,
            is_pub,
            &self.multi_shape_names,
            self.merge_config,
        );
        let try_from = fmt_struct_try_from(&struct_name, kind, spec);
        format!("{decl}\n{try_from}")
    }

    /// Emits every generated struct/impl pair ([`fmt_struct`], one per kind
    /// in `derive_ast_node_specs`'s output) followed by every generated
    /// multi-shape enum/impl pair ([`fmt_multi_shape_enum`] — one per
    /// [`ShapeName::Generated`] entry in `self.multi_shape_names`, plus one
    /// per `merge_config` `merge` entry (342.5.4): both are "one enum, one
    /// variant per kind, `TryFrom` dispatching on `node.node.kind()`", so a
    /// `merge` entry reuses the same renderer directly rather than a
    /// separate one. A [`ShapeName::MergeTarget`] entry is *not* rendered
    /// here — it names a shape whose kind set exactly matches some `merge`
    /// entry's own `from`, so that entry's own render (below) already
    /// covers it; rendering both would declare the same `enum` name twice.
    fn fmt_structs(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let specs = derive_ast_node_specs(self.grammar);
        let structs = specs
            .iter()
            .map(|(node, spec)| self.fmt_struct(node, spec))
            .collect::<Vec<_>>()
            .join("\n");
        let mut enums = self
            .multi_shape_names
            .iter()
            .filter_map(|(shape_key, shape_name)| match shape_name {
                ShapeName::Generated(name) => {
                    Some(fmt_multi_shape_enum(shape_key, name, self.merge_config))
                }
                ShapeName::MergeTarget(_) => None,
            })
            .collect::<Vec<_>>();
        if let Some(config) = self.merge_config {
            for entry in &config.merge {
                enums.push(fmt_multi_shape_enum(
                    &entry.from,
                    &entry.target,
                    self.merge_config,
                ));
            }
        }
        writeln!(f, "{}\n{}", structs, enums.join("\n"))
    }
}

impl fmt::Display for RustAst<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        self.fmt_header(f)?;
        self.fmt_pragma(f)?;
        self.fmt_node_helpers(f)?;
        self.fmt_build_error(f)?;
        self.fmt_structs(f)
    }
}

/// The sorted-named-kinds (+"$token" sentinel) key used to group
/// fields into the same multi-shape enum.
fn shape_key(target: &FieldTargetKinds) -> Vec<String> {
    let has_anonymous_token = target.anonymous_token;
    let mut sorted_named = target.named.iter().cloned().collect::<Vec<String>>();
    sorted_named.sort();
    if has_anonymous_token {
        sorted_named.push("$token".to_owned());
    }
    sorted_named
}

/// Builds one kind's struct declaration: a `` /// `{kind}` node. `` doc
/// comment, then `struct {struct_name} { ... }` — `pub` unless `is_pub` is
/// `false`, in which case an `#[allow(dead_code)]` also precedes
/// `#[derive(Debug)]`, since a non-`pub` struct's fields are no longer
/// exempt from the `dead_code` lint the way a `pub` one's are (confirmed
/// against `rustc`; see `plans/342.5.md`). An `#[allow(private_interfaces)]`
/// is also added whenever any of `spec.fields` directly references a
/// merged-away kind ([`field_directly_references_merged_kind`]) — such a
/// field's type is that kind's own (non-`pub`) struct, referenced directly
/// rather than through its merge entry's enum (see
/// [`field_rust_type`]/[`merge_entry_for_shape`] for why: widening it to
/// the enum would let the field hold a value the grammar can never actually
/// produce there). `pragma: Pragma` comes first, followed by one field per
/// entry in `spec.fields`, each typed via [`field_rust_type`].
/// `struct_name` is resolved by the caller ([`RustAst::fmt_struct`]) rather
/// than derived here, so a `passthrough` rename only needs to change that
/// one call site.
fn fmt_struct_decl(
    struct_name: &str,
    kind: &str,
    spec: &AstNodeSpec,
    is_pub: bool,
    multi_shape_names: &IndexMap<Vec<String>, ShapeName>,
    merge_config: Option<&MergeConfig>,
) -> String {
    let mut fields = vec!["    pub pragma: Pragma,".to_string()];

    fields.extend(
        spec.fields
            .iter()
            .map(|(f, f_spec)| {
                format!(
                    "    pub {}: {},",
                    f,
                    field_rust_type(f_spec, multi_shape_names, merge_config)
                )
            })
            .collect::<Vec<String>>(),
    );

    if spec.is_leaf {
        fields.push("    pub text: String,".to_string());
    }

    let fields_text = fields.join("\n");
    let vis = if is_pub { "pub " } else { "" };
    let dead_code_allow = if is_pub {
        String::new()
    } else {
        "#[allow(dead_code)]\n".to_string()
    };
    let private_interfaces_allow = if is_pub
        && spec
            .fields
            .values()
            .any(|f| field_directly_references_merged_kind(f, merge_config))
    {
        "#[allow(private_interfaces)]\n".to_string()
    } else {
        String::new()
    };

    formatdoc! {r#"
        /// `{kind}` node.
        {dead_code_allow}{private_interfaces_allow}#[derive(Debug)]
        {vis}struct {struct_name} {{
        {fields_text}
        }}
    "#}
}

/// Builds one multi-shape enum's `TryFrom<SourceNode<'tree>>` impl body:
/// an `is_named()`-gated early return to `{name}::Token(...)` when `shape`
/// includes the `"$token"` sentinel ([`shape_kinds`]), then a `match` on
/// `node.node.kind()` with one arm per real kind delegating to that kind's
/// own `TryFrom`, falling through to `BuildError::UnexpectedKind` for any
/// other kind. Each variant's payload type goes through
/// [`kind_display_name`], so a `passthrough`-renamed kind's variant still
/// names the type it's actually declared under.
fn fmt_multi_shape_enum_try_from(
    shape: &[String],
    name: &str,
    merge_config: Option<&MergeConfig>,
) -> String {
    let (clean_shape, has_token) = shape_kinds(shape);
    let match_arms = clean_shape
        .iter()
        .map(|kind| {
            format!(
                "        \"{kind}\" => Ok({name}::{}(node.try_into()?)),",
                kind_display_name(kind, merge_config)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let mut match_stmt = "match node.node.kind() {".to_string();
    if has_token {
        match_stmt = formatdoc! {r#"
            if !node.node.is_named() {{
                return Ok({name}::Token(node.text()?.to_string()));
            }}
            {match_stmt}
        "#};
    }
    match_stmt = indent(&match_stmt, 4);

    formatdoc! {r#"
        fn try_from(node: SourceNode<'tree>) -> Result<Self, Self::Error> {{
        {match_stmt}
        {match_arms}
                found => Err(BuildError::UnexpectedKind {{
                    expected: "{name}",
                    found: found.to_string(),
                }}),
            }}
        }}
    "#}
}

/// Splits a multi-shape `shape` key into its real kind names (everything
/// but the `"$token"` sentinel) and whether that sentinel was present —
/// shared by [`fmt_multi_shape_enum_decl`] and the enum's own `TryFrom`
/// dispatch, so the `"$token"` special-casing only happens in one place.
fn shape_kinds(shape: &[String]) -> (Vec<&String>, bool) {
    let has_token = shape.iter().any(|x| *x == "$token");
    (
        shape.iter().filter(|x| **x != "$token").collect(),
        has_token,
    )
}

/// Builds one multi-shape enum's declaration: `pub enum {name} { ... }`
/// with one `{Variant}({Variant})` variant per real kind in `shape`
/// ([`shape_kinds`], each name via [`kind_display_name`] so a
/// `passthrough`-renamed kind's variant matches the name it's actually
/// declared under), plus a trailing `Token(String)` variant when `shape`
/// includes the `"$token"` sentinel. Gets `#[allow(private_interfaces)]`
/// whenever any real kind in `shape` is merged-away ([`kind_is_merged_away`])
/// — true for every merge-entry-driven call ([`RustAst::fmt_structs`]) by
/// construction, and sometimes true for an ordinary phase-3 multi-shape
/// enum that happens to partially overlap a `merge` entry.
fn fmt_multi_shape_enum_decl(
    shape: &[String],
    name: &str,
    merge_config: Option<&MergeConfig>,
) -> String {
    let (clean_shape, has_token) = shape_kinds(shape);
    let mut fields = clean_shape
        .iter()
        .map(|s| {
            let n = kind_display_name(s, merge_config);
            format!("    {}({}),", n, n)
        })
        .collect::<Vec<String>>();
    if has_token {
        fields.push("    Token(String),".to_string());
    }
    let fields_lines = fields.join("\n");
    let private_interfaces_allow = if clean_shape
        .iter()
        .any(|kind| kind_is_merged_away(kind, merge_config))
    {
        "#[allow(private_interfaces)]\n"
    } else {
        ""
    };
    formatdoc! {r#"
        {private_interfaces_allow}#[derive(Debug)]
        pub enum {name} {{
        {fields_lines}
        }}
    "#}
}

/// Builds one field's construction statement inside a `TryFrom` body: a
/// `multiple` field collects every matching child via `children_by_field`
/// into a `Vec`; a single anonymous-token field reads `.text()?` as a
/// `String`; everything else (single named or multi-shape) reads one child
/// via `child_by_field` and `.try_into()`s it into its already-resolved
/// type ([`field_rust_type`]). Panics if `field`'s target resolves to no
/// possible shape at all — see [`field_rust_type`]'s own doc for why that
/// shouldn't happen.
fn field_try_from(kind: &str, field_name: &str, field: &AstFieldSpec) -> String {
    let target = &field.target;

    if field.multiple {
        formatdoc! {r#"
            let {field_name} = node
                .children_by_field("{field_name}")
                .into_iter()
                .map(|c| c.try_into())
                .collect::<Result<Vec<_>, _>>()?;
        "#}
    } else if target.named.is_empty() && target.anonymous_token {
        formatdoc! {r#"
            let {field_name} = node
                .child_by_field("{field_name}")
                .ok_or(BuildError::MissingField {{ kind: "{kind}", field: "{field_name}" }})?
                .text()?
                .to_string();
        "#}
    } else if !target.named.is_empty() {
        formatdoc! {r#"
            let {field_name} = node
                .child_by_field("{field_name}")
                .ok_or(BuildError::MissingField {{ kind: "{kind}", field: "{field_name}" }})?
                .try_into()?;
        "#}
    } else {
        unreachable!("a field always resolves to at least one target kind")
    }
}

/// The Rust type text for one field: a `merge` entry's own `target` name
/// when the field's full target set exactly matches that entry's `from`
/// ([`merge_entry_for_shape`] — this case is lossless, since the field's
/// possible kinds and the entry's variant kinds are then identical), else
/// the registered multi-shape enum name for a multi-target field, else the
/// single target kind's own name — [`kind_display_name`], so a
/// `passthrough`-renamed kind is referenced under its actual declared name
/// — else `String` for a bare anonymous token — wrapped in `Vec<...>` if
/// the field is `multiple`.
fn field_rust_type(
    field: &AstFieldSpec,
    multi_shape_names: &IndexMap<Vec<String>, ShapeName>,
    merge_config: Option<&MergeConfig>,
) -> String {
    let type_name = if let Some(entry) = merge_entry_for_shape(&field.target, merge_config) {
        entry.target.clone()
    } else if field.target.named.len() > 1
        || (!field.target.named.is_empty() && field.target.anonymous_token)
    {
        let key_shape = shape_key(&field.target);
        multi_shape_names
            .get(&key_shape)
            .map(ShapeName::name)
            .expect("shape was registered by build_multi_shape_names")
            .to_string()
    } else if field.target.named.len() == 1 && !field.target.anonymous_token {
        kind_display_name(
            field.target.named.first().expect("array length is one"),
            merge_config,
        )
    } else if field.target.named.is_empty() && field.target.anonymous_token {
        "String".to_string()
    } else {
        unreachable!("a field always resolves to at least one target kind")
    };

    if field.multiple {
        format!("Vec<{}>", type_name)
    } else {
        type_name
    }
}

/// Whether `kind` is claimed by some `merge` entry's `from` list in
/// `merge_config` — such a kind's Stage-A struct is still emitted (so
/// `enum {Target}`'s variant can wrap it and reuse its `TryFrom` impl
/// unchanged), just without `pub` ([`fmt_struct_decl`]'s `is_pub`):
/// nothing outside the generated crate should construct or name it
/// directly. `merge_config: None` (no `--merge-config` given) means no
/// kind is ever merged away.
fn kind_is_merged_away(kind: &str, merge_config: Option<&MergeConfig>) -> bool {
    merge_config.is_some_and(|config| {
        config
            .merge
            .iter()
            .any(|entry| entry.from.iter().any(|from_kind| from_kind == kind))
    })
}

/// The Rust type name a reference to `kind` should use: a `passthrough`
/// entry's `target` override if `merge_config` claims `kind` that way,
/// otherwise `pascal_case(kind)`. Every call site that names a *reference*
/// to an existing kind (as opposed to synthesizing a brand-new enum name)
/// routes through this — [`RustAst::fmt_struct`]'s own struct name,
/// [`field_rust_type`]'s single-target branch, and each multi-shape enum
/// variant's name/payload type — so a `passthrough` rename never leaves a
/// stale reference to the kind's default derived name anywhere else in the
/// generated file.
pub(crate) fn kind_display_name(kind: &str, merge_config: Option<&MergeConfig>) -> String {
    merge_config
        .and_then(|config| config.passthrough.iter().find(|entry| entry.kind == kind))
        .map(|entry| entry.target.clone())
        .unwrap_or_else(|| pascal_case(kind))
}

/// The `merge` entry, if any, whose `from` set exactly equals `target`'s
/// named-kind set — a field whose entire resolved target matches one merge
/// entry precisely should reuse that entry's own `enum` rather than
/// declaring/registering a redundant multi-shape enum for the same shape;
/// this case is lossless, since the field's possible kinds and the entry's
/// variant kinds are then identical. `check_merge_config` already
/// guarantees no kind is claimed by more than one `merge` entry, so at most
/// one entry can ever match — no ambiguity to resolve here. Returns `None`
/// for any target with an anonymous-token component, or an empty target —
/// a `merge` entry's `from` is always purely named kinds.
fn merge_entry_for_shape<'a>(
    target: &FieldTargetKinds,
    merge_config: Option<&'a MergeConfig>,
) -> Option<&'a MergeEntry> {
    if target.anonymous_token || target.named.is_empty() {
        return None;
    }
    merge_config.and_then(|config| {
        config.merge.iter().find(|entry| {
            entry.from.len() == target.named.len()
                && entry.from.iter().all(|kind| target.named.contains(kind))
        })
    })
}

/// Whether `field`'s Rust type is a merged-away kind's own (non-`pub`)
/// struct, referenced directly rather than through that kind's merge
/// entry's enum — true only for a field pinned to exactly one merged-away
/// kind whose full target does *not* exactly match some merge entry's
/// `from` set (that case is [`merge_entry_for_shape`]'s job instead, and
/// widening it to the enum here would let the field hold a value the
/// grammar can never actually produce there — see `plans/342.5.md`). A
/// `pub` struct with such a field needs `#[allow(private_interfaces)]` on
/// its own declaration ([`fmt_struct_decl`]), since the field's declared
/// type is otherwise a private type reachable through a `pub` item.
fn field_directly_references_merged_kind(
    field: &AstFieldSpec,
    merge_config: Option<&MergeConfig>,
) -> bool {
    if field.target.anonymous_token || field.target.named.len() != 1 {
        return false;
    }
    if merge_entry_for_shape(&field.target, merge_config).is_some() {
        return false;
    }
    let kind = field.target.named.first().expect("length checked above");
    kind_is_merged_away(kind, merge_config)
}

/// Rejects a `merge_config` whose `grammar`'s own root rule is claimed by a
/// `merge` entry. The scaffolded `examples/ast.rs` needs one concrete,
/// nameable, constructible root type (`use {crate}::ast::{RootKind};`); a
/// merged-away kind's struct is neither nameable (private) nor a good
/// substitute (its merge entry's enum could hold any of the entry's other
/// kinds too — the same precision-loss `field_directly_references_merged_kind`
/// avoids for ordinary fields, but there's no field here to fall back to
/// referencing the private struct directly). Called from `run_scaffold`
/// right after `check_merge_config`, before any files are written — same
/// gating pattern `check_visitor` already uses.
pub(crate) fn check_root_rule_not_merged(
    grammar: &Grammar,
    merge_config: &MergeConfig,
) -> Result<(), String> {
    let Some(root) = grammar.root_rule() else {
        return Ok(());
    };
    if kind_is_merged_away(root, Some(merge_config)) {
        return Err(format!(
            "grammar's root rule '{root}' is claimed by a `merge` entry; the scaffolded \
             example needs a concrete, nameable root type, so the root rule cannot be merged \
             away — remove it from that entry's `from` list, or use `passthrough` instead"
        ));
    }
    Ok(())
}

/// The Rust type name registered for one distinct multi-shape target-kind
/// set (see [`build_multi_shape_names`]).
#[derive(Debug)]
enum ShapeName {
    /// A phase-3-generated sum-type enum, declared once by
    /// [`fmt_multi_shape_enum`] from [`RustAst::fmt_structs`]'s own
    /// multi-shape-enum loop.
    Generated(String),
    /// This shape's kind set exactly matches a `merge` entry's own `from`
    /// set ([`merge_entry_for_shape`]) — reuses that entry's `target` name
    /// instead of declaring a redundant `enum` for the same shape; the
    /// entry's own enum, rendered once from `RustAst::fmt_structs`'s
    /// merge-entry loop, already covers it.
    MergeTarget(String),
}

impl ShapeName {
    /// The Rust name this entry resolves to, regardless of which variant.
    fn name(&self) -> &str {
        match self {
            ShapeName::Generated(name) | ShapeName::MergeTarget(name) => name,
        }
    }
}

/// Computes the Rust type name to use for each distinct "multi-shape"
/// field-target-kind set found anywhere in `grammar` — a field whose value
/// can be more than one kind (or a kind plus a bare token) needs a
/// generated sum-type enum, and two fields with the *same* possible-kinds
/// set reuse the *same* enum rather than each getting their own. A shape
/// whose kind set exactly matches some `merge` entry's own `from` set
/// ([`merge_entry_for_shape`]) reuses that entry's own `target` enum
/// instead of synthesizing a new [`ShapeName::Generated`] one — that
/// entry's enum, rendered separately, already covers it. Otherwise, naming
/// preference per shape: if every field sharing it has the same name, use
/// that name (PascalCased); otherwise fall back to a name built from the
/// shape's own kind names. Finally, validates that every name produced
/// this way — plus every real kind's own name ([`kind_display_name`], so a
/// `passthrough`-renamed kind is checked under the name it actually
/// declares), plus every `merge`/`passthrough` entry's own `target` name —
/// since all of these live as top-level Rust type names in the same
/// generated file, is distinct, returning the first collision found as
/// `Err` (see [`find_first_name_collision`]).
fn build_multi_shape_names(
    grammar: &Grammar,
    merge_config: Option<&MergeConfig>,
) -> Result<IndexMap<Vec<String>, ShapeName>, String> {
    let mut out = IndexMap::new();
    let ast_node_specs = derive_ast_node_specs(grammar);

    // create temporary map, from list of possible derivations to the fields that use them
    let mut known_shapes = IndexMap::new();
    for node_spec in ast_node_specs.values() {
        for (field, field_spec) in &node_spec.fields {
            let has_anonymous_token = field_spec.target.anonymous_token;
            if field_spec.target.named.len() > 1
                || (!field_spec.target.named.is_empty() && has_anonymous_token)
            {
                let key_shape = shape_key(&field_spec.target);
                let known_shapes_val: &mut Vec<String> = known_shapes.entry(key_shape).or_default();
                known_shapes_val.push(field.clone());
            }
        }
    }

    // compute names
    for (shape, fields) in known_shapes {
        let (clean_shape, has_token) = shape_kinds(&shape);
        let target = FieldTargetKinds {
            named: clean_shape.into_iter().cloned().collect(),
            anonymous_token: has_token,
        };
        let shape_name = match merge_entry_for_shape(&target, merge_config) {
            Some(entry) => ShapeName::MergeTarget(entry.target.clone()),
            None => ShapeName::Generated(compute_name(&shape, &fields)),
        };
        out.insert(shape, shape_name);
    }

    // Every generated struct/enum name must be distinct within the file:
    // each grammar kind gets its own `struct <Name>` (or `passthrough`
    // rename), each phase-3-generated multi-shape enum gets its own `enum
    // <Name>`, and each `merge` entry's own `target` name is also a
    // top-level Rust type name — if any two of these produce the same
    // name, the generated file won't compile. Collect a (description,
    // generated name) pair from every source and look for a repeated name.
    // A `ShapeName::MergeTarget` shape is skipped: its name is
    // *intentionally* identical to its merge entry's own name, registered
    // separately below — including it again would report a false
    // collision against itself. A `passthrough`-claimed kind is *not*
    // registered separately either: `kind_display_name` below already
    // resolves it to its `passthrough.target`, so a second entry for the
    // same target name would collide with itself.
    let mut all_names: Vec<(String, String)> = Vec::new();

    let passthrough_target = |kind: &str| -> Option<&str> {
        merge_config.and_then(|config| {
            config
                .passthrough
                .iter()
                .find(|entry| entry.kind == kind)
                .map(|entry| entry.target.as_str())
        })
    };
    for kind in ast_node_specs.keys() {
        let description = match passthrough_target(kind) {
            Some(target) => format!("passthrough entry '{kind}' -> '{target}'"),
            None => format!("kind '{kind}'"),
        };
        let generated_name = kind_display_name(kind, merge_config);
        all_names.push((description, generated_name));
    }

    for (shape, shape_name) in &out {
        if let ShapeName::Generated(name) = shape_name {
            let description = format!("shape [{}]", shape.join(", "));
            all_names.push((description, name.clone()));
        }
    }

    if let Some(config) = merge_config {
        for entry in &config.merge {
            all_names.push((
                format!("merge target '{}'", entry.target),
                entry.target.clone(),
            ));
        }
    }

    let items = all_names
        .iter()
        .map(|(description, name)| (description.as_str(), name.clone()));
    if let Some((existing, new, name)) = find_first_name_collision(items) {
        return Err(format!(
            "{existing} and {new} both generate '{name}'; rename one of them (a grammar \
             rule/field, or the `--merge-config` entry naming it) to avoid the clash"
        ));
    }

    Ok(out)
}

/// Picks one shape's enum name: `fields`' common name if every field
/// sharing this `shape` is named the same, otherwise the shape's own kind
/// names concatenated (skipping the `"$token"` sentinel a bare-token
/// possibility is marked with — see [`build_multi_shape_names`]).
fn compute_name(shape: &[String], fields: &[String]) -> String {
    // all fields have same name?
    let first = &fields[0];
    if fields.iter().all(|x| x == first) {
        pascal_case(first)
    } else {
        shape
            .iter()
            .filter(|x| *x != "$token")
            .map(|x| pascal_case(x))
            .collect::<Vec<String>>()
            .join("")
    }
}

/// Uppercases the first character of `word`, leaving the rest untouched.
fn uc_first(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        None => String::new(), // empty string, should not happen
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Converts `word` to `PascalCase`, reusing [`to_snake_case`]'s
/// word-boundary detection (camelCase, acronym runs, digit boundaries,
/// dot-separated names) rather than re-implementing it: normalize to
/// snake_case first, then uppercase each `_`-separated piece and
/// concatenate with no separator.
pub(crate) fn pascal_case(word: &str) -> String {
    let snake = to_snake_case(word);
    let words = snake
        .split('_')
        .filter(|s| !s.is_empty())
        .map(uc_first)
        .collect::<Vec<String>>();
    words.join("")
}

/// Builds one kind's full `impl<'tree> TryFrom<SourceNode<'tree>> for
/// {struct_name}` block: `let pragma = Pragma::from(node);` first, then one
/// construction statement per `spec.fields` entry ([`field_try_from`]),
/// then `let text = node.text()?.to_string();` if `spec.is_leaf`, and
/// finally `Ok({struct_name} { pragma, ... })` naming every field built
/// above. `struct_name` is resolved by the caller ([`RustAst::fmt_struct`]),
/// same as [`fmt_struct_decl`] — the two must always agree on the type
/// they're both describing, so neither derives it independently.
fn fmt_struct_try_from(struct_name: &str, kind: &str, spec: &AstNodeSpec) -> String {
    let name = struct_name;
    let mut fields_try_from = spec
        .fields
        .iter()
        .map(|(field, field_spec)| field_try_from(kind, field, field_spec))
        .collect::<Vec<String>>();
    let mut field_list = spec.fields.keys().cloned().collect::<Vec<_>>();
    if spec.is_leaf {
        fields_try_from.push("let text = node.text()?.to_string();".to_string());
        field_list.push("text".to_string());
    }

    let fields_try_from_text = indent(&fields_try_from.join(""), 8);
    let field_list_text = field_list.join(", ");

    formatdoc! {r#"
        impl<'tree> TryFrom<SourceNode<'tree>> for {name} {{
            type Error = BuildError;

            fn try_from(node: SourceNode<'tree>) -> Result<Self, Self::Error> {{
                let pragma = Pragma::from(node);
        {fields_try_from_text}
                Ok({name} {{ pragma, {field_list_text} }})
            }}
        }}
    "#}
}

/// Builds one multi-shape shape's full declaration + `impl`: the `pub enum
/// {name} { ... }` from [`fmt_multi_shape_enum_decl`], then
/// `impl<'tree> TryFrom<SourceNode<'tree>> for {name} { type Error =
/// BuildError; ... }` wrapping [`fmt_multi_shape_enum_try_from`]'s bare
/// `fn try_from` (re-indented one level via [`indent`] to sit correctly
/// inside the `impl` body). Reused directly for a `merge` entry's own enum
/// (342.5.4, called from [`RustAst::fmt_structs`] with `shape = &entry.from`
/// and `name = &entry.target`) — a per-kind merge entry and a per-field
/// multi-shape target are structurally the same thing: one enum, one
/// variant per kind, `TryFrom` dispatching on `node.node.kind()`.
fn fmt_multi_shape_enum(
    shape: &[String],
    name: &str,
    merge_config: Option<&MergeConfig>,
) -> String {
    let enum_text = fmt_multi_shape_enum_decl(shape, name, merge_config);
    let impl_text = indent(&fmt_multi_shape_enum_try_from(shape, name, merge_config), 4);

    formatdoc! {r#"
        {enum_text}
        impl<'tree> TryFrom<SourceNode<'tree>> for {name} {{
            type Error = BuildError;

        {impl_text}
        }}
    "#}
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dom::GrammarNode::{Choice, Field, TerminalLiteral, TerminalPattern, ZeroOrMore};
    use crate::dom::ast::merge::{MergeConfig, MergeEntry, PassthroughEntry};
    use crate::dom::test_utils::{nt, p};

    /// Builds a `RustAst` with `no_header: true`, for tests that don't care
    /// about the header comment.
    fn ra<'a>(grammar: &'a Grammar, source: &'a str) -> RustAst<'a> {
        RustAst::new(grammar, source, true, None).expect("grammar must be ast-safe")
    }

    /// Same as [`ra`], but with an explicit `merge_config` — for tests
    /// exercising [`kind_is_merged_away`]'s effect on struct privacy.
    fn ra_with_merge<'a>(
        grammar: &'a Grammar,
        source: &'a str,
        merge_config: &'a MergeConfig,
    ) -> RustAst<'a> {
        RustAst::new(grammar, source, true, Some(merge_config)).expect("grammar must be ast-safe")
    }

    // ── top-level assembly (fmt_header / fmt_pragma / fmt_node_helpers /
    //    fmt_build_error / fmt_structs, in `Display` order) ───────────────

    #[test]
    fn header_present_by_default() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = RustAst::new(&g, "grammar.bnf", false, None)
            .expect("grammar must be ast-safe")
            .to_string();
        let version = env!("CARGO_PKG_VERSION");
        assert!(out.starts_with(&format!(
            "// Generated by ts-bnf-tool v{version} from grammar.bnf \u{2014} do not edit by hand.\n"
        )));
    }

    #[test]
    fn header_no_header_suppresses_comment() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(!out.contains("Generated by"));
        assert!(out.starts_with("use super::visitor::SourceNode;"));
    }

    #[test]
    fn pragma_struct_and_conversion_present() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Pragma {"));
        assert!(out.contains("pub line: usize,"));
        assert!(out.contains("pub column: usize,"));
        assert!(out.contains("impl From<SourceNode<'_>> for Pragma {"));
    }

    #[test]
    fn node_helpers_present() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub fn child_by_field(&self, field_name: &str)"));
        assert!(out.contains("pub fn children_by_field(&self, field_name: &str)"));
        assert!(out.contains("pub fn text(&self) -> Result<&'tree str, BuildError>"));
    }

    #[test]
    fn build_error_present_with_three_variants() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub enum BuildError {"));
        assert!(out.contains("MissingField { kind: &'static str, field: &'static str },"));
        assert!(out.contains("UnexpectedKind { expected: &'static str, found: String },"));
        assert!(out.contains("InvalidUtf8(std::str::Utf8Error),"));
    }

    #[test]
    fn display_assembles_blocks_in_order() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        let use_pos = out.find("use super::visitor::SourceNode;").unwrap();
        let pragma_pos = out.find("pub struct Pragma {").unwrap();
        let helpers_pos = out.find("pub fn child_by_field(").unwrap();
        let error_pos = out.find("pub enum BuildError {").unwrap();
        let struct_pos = out.find("pub struct A {").unwrap();
        assert!(use_pos < pragma_pos);
        assert!(pragma_pos < helpers_pos);
        assert!(helpers_pos < error_pos);
        assert!(error_pos < struct_pos);
    }

    // ── four-way field-type breakdown ───────────────────────────────────

    #[test]
    fn single_named_field_type_is_target_struct() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: Expr,"));
        assert!(out.contains(".child_by_field(\"value\")"));
    }

    #[test]
    fn single_anonymous_field_type_is_string() {
        let g = Grammar::from_rules([p(
            "decl",
            Field("value".into(), Box::new(TerminalLiteral("'+'".into()))),
        )]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: String,"));
        assert!(out.contains(".child_by_field(\"value\")"));
        assert!(out.contains(".text()?"));
        assert!(out.contains(".to_string();"));
    }

    #[test]
    fn multi_shape_field_type_is_generated_enum_name() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: Value,"));
        assert!(out.contains("pub enum Value {"));
        assert!(out.contains("Num(Num),"));
        assert!(out.contains("Str(Str),"));
    }

    #[test]
    #[should_panic(expected = "a field always resolves to at least one target kind")]
    fn field_rust_type_panics_on_empty_target() {
        field_rust_type(&AstFieldSpec::default(), &IndexMap::new(), None);
    }

    #[test]
    #[should_panic(expected = "a field always resolves to at least one target kind")]
    fn field_try_from_panics_on_empty_target() {
        field_try_from("kind", "field", &AstFieldSpec::default());
    }

    // ── multi-shape enum naming (build_multi_shape_names) ───────────────

    #[test]
    fn build_multi_shape_names_shared_shape_reuses_one_enum() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p(
                "factor",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let names = build_multi_shape_names(&g, None).expect("no name collisions");
        assert_eq!(names.len(), 1, "one shape shared by both fields: {names:?}");
        assert_eq!(names.values().next().unwrap().name(), "Value");
    }

    #[test]
    fn build_multi_shape_names_differing_field_names_fall_back_to_shape_derived_name() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p(
                "factor",
                Field(
                    "operand".into(),
                    Box::new(Choice(vec![nt("num"), nt("str")])),
                ),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let names = build_multi_shape_names(&g, None).expect("no name collisions");
        assert_eq!(names.len(), 1);
        assert_eq!(names.values().next().unwrap().name(), "NumStr");
    }

    #[test]
    fn build_multi_shape_names_no_multi_shape_fields_returns_empty_map() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let names = build_multi_shape_names(&g, None).expect("no name collisions");
        assert!(names.is_empty());
    }

    #[test]
    fn build_multi_shape_names_synthesized_name_colliding_with_a_real_kind_is_an_error() {
        let g = Grammar::from_rules([
            p("Value", TerminalLiteral("'v'".into())),
            p(
                "x",
                Field("value".into(), Box::new(Choice(vec![nt("a"), nt("b")]))),
            ),
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
        ]);
        let err = build_multi_shape_names(&g, None).unwrap_err();
        assert!(err.contains("Value"), "error should name 'Value': {err}");
    }

    #[test]
    fn build_multi_shape_names_same_field_name_different_shapes_is_an_error() {
        let g = Grammar::from_rules([
            p(
                "x",
                Field("value".into(), Box::new(Choice(vec![nt("a"), nt("b")]))),
            ),
            p(
                "y",
                Field("value".into(), Box::new(Choice(vec![nt("c"), nt("d")]))),
            ),
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
            p("c", TerminalLiteral("'c'".into())),
            p("d", TerminalLiteral("'d'".into())),
        ]);
        let err = build_multi_shape_names(&g, None).unwrap_err();
        assert!(err.contains("shape [a, b]"), "{err}");
        assert!(err.contains("shape [c, d]"), "{err}");
    }

    // ── per-kind struct + TryFrom (fmt_struct_decl / fmt_struct_try_from) ─

    #[test]
    fn struct_multiple_field_uses_children_by_field_and_collect() {
        let g = Grammar::from_rules([
            p(
                "program",
                Field("items".into(), Box::new(ZeroOrMore(Box::new(nt("decl"))))),
            ),
            p("decl", TerminalLiteral("'d'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub items: Vec<Decl>,"));
        assert!(out.contains(".children_by_field(\"items\")"));
        assert!(out.contains(".collect::<Result<Vec<_>, _>>()?;"));
    }

    #[test]
    fn struct_leaf_kind_gets_text_field_and_text_call() {
        let g = Grammar::from_rules([p("num", TerminalPattern("/[0-9]+/".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Num {"));
        assert!(out.contains("pub text: String,"));
        assert!(out.contains("let text = node.text()?.to_string();"));
        assert!(out.contains("Ok(Num { pragma, text })"));
    }

    #[test]
    fn struct_single_field_uses_child_by_field_and_missing_field_error() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains(".child_by_field(\"value\")"));
        assert!(out.contains("BuildError::MissingField { kind: \"decl\", field: \"value\" }"));
    }

    // ── merge-config privacy (kind_is_merged_away / fmt_struct_decl) ────

    /// A grammar with two kinds, one of which a `MergeConfig` claims via a
    /// `merge` entry — used across the tests below.
    fn merge_grammar_and_config() -> (Grammar, MergeConfig) {
        let g = Grammar::from_rules([
            p("for_statement", TerminalLiteral("'f'".into())),
            p("while_statement", TerminalLiteral("'w'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec!["for_statement".to_string(), "while_statement".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        (g, config)
    }

    /// A kind claimed by a `merge` entry is emitted as a private struct
    /// (no `pub`), not the `pub struct` phase 3 emits by default.
    #[test]
    fn merged_kind_struct_is_not_pub() {
        let (g, config) = merge_grammar_and_config();
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(!out.contains("pub struct ForStatement {"));
        assert!(out.contains("struct ForStatement {"));
    }

    /// A merged-away struct's `#[allow(dead_code)]` precedes
    /// `#[derive(Debug)]`, directly above the (non-`pub`) struct
    /// declaration — confirmed against `rustc` in `plans/342.5.md` as
    /// necessary once the struct itself is no longer `pub`.
    #[test]
    fn merged_kind_struct_has_allow_dead_code() {
        let (g, config) = merge_grammar_and_config();
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("#[allow(dead_code)]\n#[derive(Debug)]\nstruct ForStatement {"));
    }

    /// A merged-away kind's `TryFrom` impl is unaffected by privacy — `impl`
    /// blocks carry no visibility modifier in Rust, so phase 3's
    /// `fmt_struct_try_from` output is reused completely unchanged.
    #[test]
    fn merged_kind_try_from_impl_unaffected_by_privacy() {
        let (g, config) = merge_grammar_and_config();
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for ForStatement {"));
        assert!(out.contains("Ok(ForStatement { pragma, text })"));
    }

    /// A kind no `merge` entry claims stays `pub`, even when `merge_config`
    /// is `Some` and claims a *different* kind.
    #[test]
    fn unclaimed_kind_with_merge_config_present_stays_pub() {
        let g = Grammar::from_rules([
            p("for_statement", TerminalLiteral("'f'".into())),
            p("comment", TerminalLiteral("'c'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec!["for_statement".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("pub struct Comment {"));
        assert!(!out.contains("#[allow(dead_code)]\n#[derive(Debug)]\nstruct Comment {"));
    }

    // ── merge-config enum emission (342.5.4) ─────────────────────────────

    /// The full worked `Loop` example from `plans/342.5.md`: three kinds
    /// merged into one `pub enum`, each variant wrapping that kind's own
    /// (now-private) struct and reusing its unchanged `TryFrom` impl.
    #[test]
    fn merge_entry_emits_pub_enum_with_variant_per_kind_and_try_from_dispatch() {
        let g = Grammar::from_rules([
            p("for_statement", TerminalLiteral("'f'".into())),
            p("while_statement", TerminalLiteral("'w'".into())),
            p("repeat_statement", TerminalLiteral("'r'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec![
                    "for_statement".to_string(),
                    "while_statement".to_string(),
                    "repeat_statement".to_string(),
                ],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();

        assert!(!out.contains("pub struct ForStatement {"));
        assert!(!out.contains("pub struct WhileStatement {"));
        assert!(!out.contains("pub struct RepeatStatement {"));

        assert!(out.contains("#[allow(private_interfaces)]\n#[derive(Debug)]\npub enum Loop {"));
        assert!(out.contains("ForStatement(ForStatement),"));
        assert!(out.contains("WhileStatement(WhileStatement),"));
        assert!(out.contains("RepeatStatement(RepeatStatement),"));

        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for Loop {"));
        assert!(out.contains("\"for_statement\" => Ok(Loop::ForStatement(node.try_into()?)),"));
        assert!(out.contains("\"while_statement\" => Ok(Loop::WhileStatement(node.try_into()?)),"));
        assert!(
            out.contains("\"repeat_statement\" => Ok(Loop::RepeatStatement(node.try_into()?)),")
        );
        assert!(out.contains("expected: \"Loop\","));

        // Each merged kind's own `TryFrom` is phase 3's unchanged output.
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for ForStatement {"));
        assert!(out.contains("Ok(ForStatement { pragma, text })"));
    }

    // ── passthrough (342.5.5) ─────────────────────────────────────────────

    /// A `passthrough` entry renames a kind's generated type, staying
    /// `pub` and otherwise unchanged from phase 3's ordinary rendering.
    #[test]
    fn passthrough_renames_struct_and_try_from_target_stays_pub() {
        let g = Grammar::from_rules([p("comment", TerminalLiteral("'c'".into()))]);
        let config = MergeConfig {
            merge: vec![],
            passthrough: vec![PassthroughEntry {
                kind: "comment".to_string(),
                target: "DocComment".to_string(),
            }],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("pub struct DocComment {"));
        assert!(!out.contains("struct Comment {"));
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for DocComment {"));
        assert!(out.contains("Ok(DocComment { pragma, text })"));
    }

    // ── field-type resolution gap fix (342.5.13) ─────────────────────────

    /// Rule 1: a field elsewhere in the grammar whose sole target is a
    /// `passthrough`-renamed kind gets that kind's *renamed* type, never
    /// its stale default-derived name.
    #[test]
    fn field_referencing_passthrough_renamed_kind_uses_renamed_type() {
        let g = Grammar::from_rules([
            p("comment", TerminalLiteral("'c'".into())),
            p("decl", Field("doc".into(), Box::new(nt("comment")))),
        ]);
        let config = MergeConfig {
            merge: vec![],
            passthrough: vec![PassthroughEntry {
                kind: "comment".to_string(),
                target: "DocComment".to_string(),
            }],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("pub doc: DocComment,"));
        assert!(!out.contains("pub doc: Comment,"));
    }

    /// Rule 2: a field whose full target set exactly matches a `merge`
    /// entry's `from` set gets that entry's own enum type, and that enum
    /// is declared exactly once — no duplicate/redundant `enum Loop`.
    #[test]
    fn field_matching_full_merge_entry_shape_reuses_merge_enum_exactly_once() {
        let g = Grammar::from_rules([
            p("for_statement", TerminalLiteral("'f'".into())),
            p("while_statement", TerminalLiteral("'w'".into())),
            p(
                "stmt",
                Field(
                    "body".into(),
                    Box::new(Choice(vec![nt("for_statement"), nt("while_statement")])),
                ),
            ),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec!["for_statement".to_string(), "while_statement".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("pub body: Loop,"));
        assert_eq!(
            out.matches("pub enum Loop {").count(),
            1,
            "enum Loop must be declared exactly once: {out}"
        );
    }

    /// Rule 3: a field pinned to exactly one merged-away kind (not the
    /// entry's full choice) keeps referencing that kind's own precise
    /// (private) struct type, rather than being widened to the lossy
    /// merge-enum — and the *containing* struct gets
    /// `#[allow(private_interfaces)]` since it now has a `pub` field of a
    /// private type.
    #[test]
    fn field_referencing_single_merged_away_kind_keeps_precise_type() {
        let g = Grammar::from_rules([
            p("for_statement", TerminalLiteral("'f'".into())),
            p("while_statement", TerminalLiteral("'w'".into())),
            p(
                "outer",
                Field("loop_part".into(), Box::new(nt("for_statement"))),
            ),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec!["for_statement".to_string(), "while_statement".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let out = ra_with_merge(&g, "g", &config).to_string();
        assert!(out.contains("pub loop_part: ForStatement,"));
        assert!(!out.contains("pub loop_part: Loop,"));
        assert!(out.contains("#[allow(private_interfaces)]\n#[derive(Debug)]\npub struct Outer {"));
    }

    // ── Rust-identifier collision checks (merge/passthrough targets) ─────

    #[test]
    fn build_multi_shape_names_merge_target_colliding_with_real_kind_is_an_error() {
        let g = Grammar::from_rules([
            p("Loop", TerminalLiteral("'l'".into())),
            p("for_statement", TerminalLiteral("'f'".into())),
            p("while_statement", TerminalLiteral("'w'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Loop".to_string(),
                from: vec!["for_statement".to_string(), "while_statement".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let err = build_multi_shape_names(&g, Some(&config)).unwrap_err();
        assert!(err.contains("kind 'Loop'"), "{err}");
        assert!(err.contains("merge target 'Loop'"), "{err}");
    }

    #[test]
    fn build_multi_shape_names_passthrough_target_colliding_with_real_kind_is_an_error() {
        let g = Grammar::from_rules([
            p("expr", TerminalLiteral("'e'".into())),
            p("comment", TerminalLiteral("'c'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![],
            passthrough: vec![PassthroughEntry {
                kind: "comment".to_string(),
                target: "Expr".to_string(),
            }],
            ignore: vec![],
        };
        let err = build_multi_shape_names(&g, Some(&config)).unwrap_err();
        assert!(err.contains("kind 'expr'"), "{err}");
        assert!(err.contains("passthrough entry 'comment'"), "{err}");
    }

    #[test]
    fn build_multi_shape_names_merge_target_colliding_with_generated_shape_name_is_an_error() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
        ]);
        let config = MergeConfig {
            merge: vec![MergeEntry {
                target: "Value".to_string(),
                from: vec!["a".to_string(), "b".to_string()],
            }],
            passthrough: vec![],
            ignore: vec![],
        };
        let err = build_multi_shape_names(&g, Some(&config)).unwrap_err();
        assert!(err.contains("shape [num, str]"), "{err}");
        assert!(err.contains("merge target 'Value'"), "{err}");
    }

    // ── multi-shape enum dispatch (fmt_multi_shape_enum_try_from) ───────

    #[test]
    fn multi_shape_enum_dispatch_checks_is_named_when_token_variant_present() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field(
                    "value".into(),
                    Box::new(Choice(vec![nt("num"), TerminalLiteral("'+'".into())])),
                ),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("Token(String),"));
        assert!(out.contains("if !node.node.is_named() {"));
        assert!(out.contains("return Ok(Value::Token(node.text()?.to_string()));"));
    }

    #[test]
    fn multi_shape_enum_dispatch_omits_is_named_check_without_token_variant() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(!out.contains("is_named()"));
    }

    #[test]
    fn multi_shape_enum_dispatch_has_one_arm_per_kind_and_unexpected_kind_fallback() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("\"num\" => Ok(Value::Num(node.try_into()?)),"));
        assert!(out.contains("\"str\" => Ok(Value::Str(node.try_into()?)),"));
        assert!(out.contains("found => Err(BuildError::UnexpectedKind {"));
        assert!(out.contains("expected: \"Value\","));
    }

    // ── Known v1 limitation: unlabeled top-level choice ─────────────────

    /// A non-leaf kind whose body is an unlabeled top-level choice among
    /// visible nonterminals derives a struct with *no* fields beyond
    /// `pragma` — deliberate (see "Known v1 limitation" in
    /// `plans/342.3.md`), not a panic or a warning. This test documents
    /// that as intentional, so it doesn't look like a regression later.
    #[test]
    fn known_v1_limitation_unlabeled_top_level_choice_yields_pragma_only_struct() {
        let g = Grammar::from_rules([
            p("statement", Choice(vec![nt("loop_stmt"), nt("if_stmt")])),
            p("loop_stmt", TerminalLiteral("'l'".into())),
            p("if_stmt", TerminalLiteral("'i'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Statement {\n    pub pragma: Pragma,\n}"));
        assert!(out.contains("Ok(Statement { pragma,  })"));
    }

    // ── #[derive(Debug)] on every generated type ────────────────────────

    #[test]
    fn every_generated_type_derives_debug() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("#[derive(Debug)]\npub struct Pragma {"));
        assert!(out.contains("#[derive(Debug)]\npub struct Decl {"));
        assert!(out.contains("#[derive(Debug)]\npub enum Value {"));
    }

    // ── independent kinds don't share a mechanically-copied impl ────────

    #[test]
    fn each_leaf_kind_gets_its_own_independent_try_from_impl() {
        let g = Grammar::from_rules([
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for A {"));
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for B {"));
        assert!(out.contains("Ok(A { pragma, text })"));
        assert!(out.contains("Ok(B { pragma, text })"));
    }
}
