use crate::dom::FieldTargetKinds;
use crate::dom::ast::{AstFieldSpec, AstNodeSpec};
use crate::dom::{
    Grammar, ast::derive_ast_node_specs, visitor::text::indent, visitor::to_snake_case,
};
use crate::util::find_first_name_collision;
use indexmap::IndexMap;
use indoc::{formatdoc, indoc};
use std::fmt::{self, Formatter};

/// Renders a [`Grammar`]'s derived AST-struct shape (see [`super`]) as a
/// complete Rust source file: one typed struct/enum plus a
/// `TryFrom<SourceNode<'tree>>` impl per node kind, sharing one
/// `BuildError` across all of them.
///
/// Only buildable via [`RustAst::new`] — see its own doc comment for why.
pub struct RustAst<'a> {
    /// The grammar to derive the AST types from
    grammar: &'a Grammar,
    /// The source filename shown in the generated-file header (`<stdin>` for stdin).
    source: &'a str,
    /// When `true`, suppress the generated-file header comment.
    no_header: bool,
    /// Enum name for each distinct multi-shape target-kind set, keyed by
    /// the sorted kind names — see "Resolved: multi-shape enum naming"
    /// below. Built once, here, not recomputed per field.
    multi_shape_names: IndexMap<Vec<String>, String>,
}

impl<'a> RustAst<'a> {
    /// Builds a `RustAst` for `grammar`, computing the multi-shape enum
    /// naming table ([`build_multi_shape_names`]) up front so every
    /// per-kind struct emitted later can look a field's type up rather
    /// than deriving it — see "Resolved: multi-shape enum naming".
    ///
    /// - `source`: the source filename shown in the generated-file header
    ///   (`<stdin>` for stdin).
    /// - `no_header`: when `true`, suppresses the generated-file header
    ///   comment.
    pub fn new(grammar: &'a Grammar, source: &'a str, no_header: bool) -> Result<Self, String> {
        let multi_shape_names = build_multi_shape_names(grammar)?;
        Ok(Self {
            grammar,
            source,
            no_header,
            multi_shape_names,
        })
    }
}

impl RustAst<'_> {
    /// Emits `use super::visitor::SourceNode;` — the first line of real
    /// content in the generated file, right after `fmt_header`'s
    /// comment/blank-line pair — followed by the `Pragma` struct and its
    /// `From<SourceNode<'_>>` impl. `Pragma` stores 1-indexed
    /// `line`/`column` (tree-sitter itself is 0-indexed; this converts
    /// once here).
    fn fmt_pragma(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            use super::visitor::SourceNode;

            /// A node's start position in its source file.
            /// 1-indexed (tree-sitter uses 0-index; this converts once here).
            #[derive(Debug)]
            pub struct Pragma {
                pub line: usize,
                pub column: usize,
            }

            impl From<SourceNode<'_>> for Pragma {
                fn from(node: SourceNode<'_>) -> Self {
                    let point = node.node.start_position();
                    Pragma { line: point.row + 1, column: point.column + 1 }
                }
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Emits the generated-file header comment, unless suppressed by
    /// `no_header` — identical wording to [`super::super::GrammarJs`]'s, since
    /// this is also generated code that shouldn't be hand-edited. Unlike
    /// `GrammarJs::fmt_header`, a blank line follows the comment: the next
    /// thing emitted is a Rust `use` statement, and comment-blank-`use` reads
    /// more naturally than comment-immediately-`use`.
    fn fmt_header(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.no_header {
            let version = env!("CARGO_PKG_VERSION");
            writeln!(
                f,
                "// Generated by ts-bnf-tool v{version} from {} \u{2014} do not edit by hand.",
                self.source
            )?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits a second `impl<'tree> SourceNode<'tree>` block (`visitor.rs`
    /// defines the struct itself; this only adds inherent methods) with
    /// the three helpers every generated `TryFrom` impl needs:
    /// `child_by_field` and `children_by_field` for single-target and
    /// `multiple: true` fields respectively, and `text` for a leaf kind's
    /// own source text.
    fn fmt_node_helpers(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            impl<'tree> SourceNode<'tree> {
                /// The child at `field_name`, if present, bundled with this node's
                /// own source text.
                pub fn child_by_field(&self, field_name: &str) -> Option<SourceNode<'tree>> {
                    self.node
                        .child_by_field_name(field_name)
                        .map(|node| SourceNode { node, source: self.source })
                }
            
                /// Every child at `field_name`, in declaration order, each bundled
                /// with this node's own source text — for `multiple: true` fields
                /// (`Vec<T>`); see the worked example above.
                pub fn children_by_field(&self, field_name: &str) -> Vec<SourceNode<'tree>> {
                    let mut cursor = self.node.walk();
                    self.node
                        .children_by_field_name(field_name, &mut cursor)
                        .map(|node| SourceNode { node, source: self.source })
                        .collect()
                }
            
                /// This node's own source text — for a leaf kind's `text: String` field.
                pub fn text(&self) -> Result<&'tree str, BuildError> {
                    self.node
                        .utf8_text(self.source.as_bytes())
                        .map_err(BuildError::InvalidUtf8)
                }
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Emits `BuildError`, the error type shared by every generated
    /// `TryFrom` impl: a required field absent from a node
    /// (`MissingField`), a multi-shape field's child with a kind outside
    /// its declared set (`UnexpectedKind`), or a leaf node's text not
    /// being valid UTF-8 (`InvalidUtf8`, defensive — shouldn't happen for
    /// a grammar's own tokenizer output).
    fn fmt_build_error(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let body = indoc! {r#"
            /// An error building a typed AST node from a parsed tree.
            #[derive(Debug)]
            pub enum BuildError {
                /// A field the grammar guarantees is present was absent on this
                /// particular node — shouldn't happen for a tree that parsed without
                /// errors, but `child_by_field` returns `Option`, so this is what a
                /// `None` becomes.
                MissingField { kind: &'static str, field: &'static str },
                /// A multi-shape field's child had a kind outside its declared
                /// target-kind set.
                UnexpectedKind { expected: &'static str, found: String },
                /// A leaf node's text was not valid UTF-8 — a grammar's own tokenizer
                /// should only ever produce valid UTF-8 out of valid UTF-8 source, so
                /// this is defensive, not expected in practice.
                InvalidUtf8(std::str::Utf8Error),
            }
        "#};
        writeln!(f, "{}", body)
    }

    /// Builds one kind's full declaration + `impl`: [`fmt_struct_decl`]
    /// (using `self.multi_shape_names` to resolve multi-shape field
    /// types), then [`fmt_struct_try_from`] — which, unlike
    /// [`fmt_multi_shape_enum`]'s `try_from` half, already returns its own
    /// complete `impl` block at one consistent scale, so no `indent()`
    /// step is needed here.
    fn fmt_struct(&self, kind: &str, spec: &AstNodeSpec) -> String {
        let decl = fmt_struct_decl(kind, spec, &self.multi_shape_names);
        let try_from = fmt_struct_try_from(kind, spec);
        format!("{decl}\n{try_from}")
    }

    /// Emits every generated struct/impl pair ([`fmt_struct`], one per kind
    /// in `derive_ast_node_specs`'s output) followed by every generated
    /// multi-shape enum/impl pair ([`fmt_multi_shape_enum`], one per entry
    /// in `self.multi_shape_names`) — the last of the five blocks `Display`
    /// assembles the generated file from.
    fn fmt_structs(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let specs = derive_ast_node_specs(self.grammar);
        let structs = specs
            .iter()
            .map(|(node, spec)| self.fmt_struct(node, spec))
            .collect::<Vec<_>>()
            .join("\n");
        let enums = self
            .multi_shape_names
            .iter()
            .map(|(shape_key, shape_name)| fmt_multi_shape_enum(shape_key, shape_name))
            .collect::<Vec<_>>()
            .join("\n");
        writeln!(f, "{}\n{}", structs, enums)
    }
}

impl fmt::Display for RustAst<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        self.fmt_header(f)?;
        self.fmt_pragma(f)?;
        self.fmt_node_helpers(f)?;
        self.fmt_build_error(f)?;
        self.fmt_structs(f)
    }
}

/// The sorted-named-kinds (+"$token" sentinel) key used to group
/// fields into the same multi-shape enum.
fn shape_key(target: &FieldTargetKinds) -> Vec<String> {
    let has_anonymous_token = target.anonymous_token;
    let mut sorted_named = target.named.iter().cloned().collect::<Vec<String>>();
    sorted_named.sort();
    if has_anonymous_token {
        sorted_named.push("$token".to_owned());
    }
    sorted_named
}

/// Builds one kind's struct declaration: a `` /// `{kind}` node. `` doc
/// comment, then `pub struct <PascalKind> { ... }` with `pragma: Pragma`
/// first, followed by one field per entry in `spec.fields`, each typed via
/// [`field_rust_type`].
fn fmt_struct_decl(
    kind: &str,
    spec: &AstNodeSpec,
    multi_shape_names: &IndexMap<Vec<String>, String>,
) -> String {
    let struct_name = pascal_case(kind);
    let mut fields = vec!["    pub pragma: Pragma,".to_string()];

    fields.extend(
        spec.fields
            .iter()
            .map(|(f, f_spec)| {
                format!(
                    "    pub {}: {},",
                    f,
                    field_rust_type(f_spec, multi_shape_names)
                )
            })
            .collect::<Vec<String>>(),
    );

    if spec.is_leaf {
        fields.push("    pub text: String,".to_string());
    }

    let fields_text = fields.join("\n");

    formatdoc! {r#"
        /// `{kind}` node.
        #[derive(Debug)]
        pub struct {struct_name} {{
        {fields_text}
        }}
    "#}
}

/// Builds one multi-shape enum's `TryFrom<SourceNode<'tree>>` impl body:
/// an `is_named()`-gated early return to `{name}::Token(...)` when `shape`
/// includes the `"$token"` sentinel ([`shape_kinds`]), then a `match` on
/// `node.node.kind()` with one arm per real kind delegating to that kind's
/// own `TryFrom`, falling through to `BuildError::UnexpectedKind` for any
/// other kind.
fn fmt_multi_shape_enum_try_from(shape: &[String], name: &str) -> String {
    let (clean_shape, has_token) = shape_kinds(shape);
    let match_arms = clean_shape
        .iter()
        .map(|kind| {
            format!(
                "        \"{kind}\" => Ok({name}::{}(node.try_into()?)),",
                pascal_case(kind)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let mut match_stmt = "match node.node.kind() {".to_string();
    if has_token {
        match_stmt = formatdoc! {r#"
            if !node.node.is_named() {{
                return Ok({name}::Token(node.text()?.to_string()));
            }}
            {match_stmt}
        "#};
    }
    match_stmt = indent(&match_stmt, 4);

    formatdoc! {r#"
        fn try_from(node: SourceNode<'tree>) -> Result<Self, Self::Error> {{
        {match_stmt}
        {match_arms}
                found => Err(BuildError::UnexpectedKind {{
                    expected: "{name}",
                    found: found.to_string(),
                }}),
            }}
        }}
    "#}
}

/// Splits a multi-shape `shape` key into its real kind names (everything
/// but the `"$token"` sentinel) and whether that sentinel was present —
/// shared by [`fmt_multi_shape_enum_decl`] and the enum's own `TryFrom`
/// dispatch, so the `"$token"` special-casing only happens in one place.
fn shape_kinds(shape: &[String]) -> (Vec<&String>, bool) {
    let has_token = shape.iter().any(|x| *x == "$token");
    (
        shape.iter().filter(|x| **x != "$token").collect(),
        has_token,
    )
}

/// Builds one multi-shape enum's declaration: `pub enum {name} { ... }`
/// with one `{PascalKind}({PascalKind})` variant per real kind in `shape`
/// ([`shape_kinds`]), plus a trailing `Token(String)` variant when `shape`
/// includes the `"$token"` sentinel.
fn fmt_multi_shape_enum_decl(shape: &[String], name: &str) -> String {
    let (clean_shape, has_token) = shape_kinds(shape);
    let mut fields = clean_shape
        .iter()
        .map(|s| {
            let n = pascal_case(s);
            format!("    {}({}),", n, n)
        })
        .collect::<Vec<String>>();
    if has_token {
        fields.push("    Token(String),".to_string());
    }
    let fields_lines = fields.join("\n");
    formatdoc! {r#"
        #[derive(Debug)]
        pub enum {name} {{
        {fields_lines}
        }}
    "#}
}

/// Builds one field's construction statement inside a `TryFrom` body: a
/// `multiple` field collects every matching child via `children_by_field`
/// into a `Vec`; a single anonymous-token field reads `.text()?` as a
/// `String`; everything else (single named or multi-shape) reads one child
/// via `child_by_field` and `.try_into()`s it into its already-resolved
/// type ([`field_rust_type`]). Panics if `field`'s target resolves to no
/// possible shape at all — see [`field_rust_type`]'s own doc for why that
/// shouldn't happen.
fn field_try_from(kind: &str, field_name: &str, field: &AstFieldSpec) -> String {
    let target = &field.target;

    if field.multiple {
        formatdoc! {r#"
            let {field_name} = node
                .children_by_field("{field_name}")
                .into_iter()
                .map(|c| c.try_into())
                .collect::<Result<Vec<_>, _>>()?;
        "#}
    } else if target.named.is_empty() && target.anonymous_token {
        formatdoc! {r#"
            let {field_name} = node
                .child_by_field("{field_name}")
                .ok_or(BuildError::MissingField {{ kind: "{kind}", field: "{field_name}" }})?
                .text()?
                .to_string();
        "#}
    } else if !target.named.is_empty() {
        formatdoc! {r#"
            let {field_name} = node
                .child_by_field("{field_name}")
                .ok_or(BuildError::MissingField {{ kind: "{kind}", field: "{field_name}" }})?
                .try_into()?;
        "#}
    } else {
        unreachable!("a field always resolves to at least one target kind")
    }
}

/// The Rust type text for one field: the multi-shape enum name for a
/// multi-target field, the single target kind's own struct name, or
/// `String` for a bare anonymous token - wrapped in `Vec<...>` if the
/// field is `multiple`
fn field_rust_type(
    field: &AstFieldSpec,
    multi_shape_names: &IndexMap<Vec<String>, String>,
) -> String {
    let type_name = if field.target.named.len() > 1
        || (!field.target.named.is_empty() && field.target.anonymous_token)
    {
        let key_shape = shape_key(&field.target);
        multi_shape_names
            .get(&key_shape)
            .cloned()
            .expect("shape was registered by build_multi_shape_names")
    } else if field.target.named.len() == 1 && !field.target.anonymous_token {
        pascal_case(field.target.named.first().expect("array length is one"))
    } else if field.target.named.is_empty() && field.target.anonymous_token {
        "String".to_string()
    } else {
        unreachable!("a field always resolves to at least one target kind")
    };

    if field.multiple {
        format!("Vec<{}>", type_name)
    } else {
        type_name
    }
}

/// Computes the Rust enum name to use for each distinct "multi-shape"
/// field-target-kind set found anywhere in `grammar` — a field whose value
/// can be more than one kind (or a kind plus a bare token) needs a
/// generated sum-type enum, and two fields with the *same* possible-kinds
/// set reuse the *same* enum rather than each getting their own. Naming
/// preference, per shape: if every field sharing it has the same name, use
/// that name (PascalCased); otherwise fall back to a name built from the
/// shape's own kind names. Finally, validates that every name produced
/// this way — plus every real kind's own struct name, since both live as
/// top-level Rust type names in the same generated file — is distinct,
/// returning the first collision found as `Err` (see
/// [`find_first_name_collision`]).
fn build_multi_shape_names(grammar: &Grammar) -> Result<IndexMap<Vec<String>, String>, String> {
    let mut out = IndexMap::new();
    let ast_node_specs = derive_ast_node_specs(grammar);

    // create temporary map, from list of possible derivations to the fields that use them
    let mut known_shapes = IndexMap::new();
    for node_spec in ast_node_specs.values() {
        for (field, field_spec) in &node_spec.fields {
            let has_anonymous_token = field_spec.target.anonymous_token;
            if field_spec.target.named.len() > 1
                || (!field_spec.target.named.is_empty() && has_anonymous_token)
            {
                let key_shape = shape_key(&field_spec.target);
                let known_shapes_val: &mut Vec<String> = known_shapes.entry(key_shape).or_default();
                known_shapes_val.push(field.clone());
            }
        }
    }

    // compute names
    for (shape, fields) in known_shapes {
        let name = compute_name(&shape, &fields);
        out.insert(shape, name);
    }

    // Every generated struct/enum name must be distinct within the file:
    // each grammar kind gets its own `struct <Name>`, and each multi-shape
    // enum named above gets its own `enum <Name>` — if any two of these
    // produce the same name, the generated file won't compile. Collect a
    // (description, generated name) pair from both sources and look for a
    // repeated name.
    let mut all_names: Vec<(String, String)> = Vec::new();

    for kind in ast_node_specs.keys() {
        let description = format!("kind '{kind}'");
        let generated_name = pascal_case(kind);
        all_names.push((description, generated_name));
    }

    for (shape, name) in &out {
        let description = format!("shape [{}]", shape.join(", "));
        all_names.push((description, name.clone()));
    }

    let items = all_names
        .iter()
        .map(|(description, name)| (description.as_str(), name.clone()));
    if let Some((existing, new, name)) = find_first_name_collision(items) {
        return Err(format!(
            "{existing} and {new} both generate '{name}'; rename one of the \
             rules (or its field) to avoid the clash"
        ));
    }

    Ok(out)
}

/// Picks one shape's enum name: `fields`' common name if every field
/// sharing this `shape` is named the same, otherwise the shape's own kind
/// names concatenated (skipping the `"$token"` sentinel a bare-token
/// possibility is marked with — see [`build_multi_shape_names`]).
fn compute_name(shape: &[String], fields: &[String]) -> String {
    // all fields have same name?
    let first = &fields[0];
    if fields.iter().all(|x| x == first) {
        pascal_case(first)
    } else {
        shape
            .iter()
            .filter(|x| *x != "$token")
            .map(|x| pascal_case(x))
            .collect::<Vec<String>>()
            .join("")
    }
}

/// Uppercases the first character of `word`, leaving the rest untouched.
fn uc_first(word: &str) -> String {
    let mut chars = word.chars();
    match chars.next() {
        None => String::new(), // empty string, should not happen
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Converts `word` to `PascalCase`, reusing [`to_snake_case`]'s
/// word-boundary detection (camelCase, acronym runs, digit boundaries,
/// dot-separated names) rather than re-implementing it: normalize to
/// snake_case first, then uppercase each `_`-separated piece and
/// concatenate with no separator.
pub(crate) fn pascal_case(word: &str) -> String {
    let snake = to_snake_case(word);
    let words = snake
        .split('_')
        .filter(|s| !s.is_empty())
        .map(uc_first)
        .collect::<Vec<String>>();
    words.join("")
}

/// Builds one kind's full `impl<'tree> TryFrom<SourceNode<'tree>> for
/// {PascalKind}` block: `let pragma = Pragma::from(node);` first, then one
/// construction statement per `spec.fields` entry ([`field_try_from`]),
/// then `let text = node.text()?.to_string();` if `spec.is_leaf`, and
/// finally `Ok({PascalKind} { pragma, ... })` naming every field built
/// above.
fn fmt_struct_try_from(kind: &str, spec: &AstNodeSpec) -> String {
    let name = pascal_case(kind);
    let mut fields_try_from = spec
        .fields
        .iter()
        .map(|(field, field_spec)| field_try_from(kind, field, field_spec))
        .collect::<Vec<String>>();
    let mut field_list = spec.fields.keys().cloned().collect::<Vec<_>>();
    if spec.is_leaf {
        fields_try_from.push("let text = node.text()?.to_string();".to_string());
        field_list.push("text".to_string());
    }

    let fields_try_from_text = indent(&fields_try_from.join(""), 8);
    let field_list_text = field_list.join(", ");

    formatdoc! {r#"
        impl<'tree> TryFrom<SourceNode<'tree>> for {name} {{
            type Error = BuildError;

            fn try_from(node: SourceNode<'tree>) -> Result<Self, Self::Error> {{
                let pragma = Pragma::from(node);
        {fields_try_from_text}
                Ok({name} {{ pragma, {field_list_text} }})
            }}
        }}
    "#}
}

/// Builds one multi-shape shape's full declaration + `impl`: the `pub enum
/// {name} { ... }` from [`fmt_multi_shape_enum_decl`], then
/// `impl<'tree> TryFrom<SourceNode<'tree>> for {name} { type Error =
/// BuildError; ... }` wrapping [`fmt_multi_shape_enum_try_from`]'s bare
/// `fn try_from` (re-indented one level via [`indent`] to sit correctly
/// inside the `impl` body).
fn fmt_multi_shape_enum(shape: &[String], name: &str) -> String {
    let enum_text = fmt_multi_shape_enum_decl(shape, name);
    let impl_text = indent(&fmt_multi_shape_enum_try_from(shape, name), 4);

    formatdoc! {r#"
        {enum_text}
        impl<'tree> TryFrom<SourceNode<'tree>> for {name} {{
            type Error = BuildError;

        {impl_text}
        }}
    "#}
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dom::GrammarNode::{Choice, Field, TerminalLiteral, TerminalPattern, ZeroOrMore};
    use crate::dom::test_utils::{nt, p};

    /// Builds a `RustAst` with `no_header: true`, for tests that don't care
    /// about the header comment.
    fn ra<'a>(grammar: &'a Grammar, source: &'a str) -> RustAst<'a> {
        RustAst::new(grammar, source, true).expect("grammar must be ast-safe")
    }

    // ── top-level assembly (fmt_header / fmt_pragma / fmt_node_helpers /
    //    fmt_build_error / fmt_structs, in `Display` order) ───────────────

    #[test]
    fn header_present_by_default() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = RustAst::new(&g, "grammar.bnf", false)
            .expect("grammar must be ast-safe")
            .to_string();
        let version = env!("CARGO_PKG_VERSION");
        assert!(out.starts_with(&format!(
            "// Generated by ts-bnf-tool v{version} from grammar.bnf \u{2014} do not edit by hand.\n"
        )));
    }

    #[test]
    fn header_no_header_suppresses_comment() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(!out.contains("Generated by"));
        assert!(out.starts_with("use super::visitor::SourceNode;"));
    }

    #[test]
    fn pragma_struct_and_conversion_present() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Pragma {"));
        assert!(out.contains("pub line: usize,"));
        assert!(out.contains("pub column: usize,"));
        assert!(out.contains("impl From<SourceNode<'_>> for Pragma {"));
    }

    #[test]
    fn node_helpers_present() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub fn child_by_field(&self, field_name: &str)"));
        assert!(out.contains("pub fn children_by_field(&self, field_name: &str)"));
        assert!(out.contains("pub fn text(&self) -> Result<&'tree str, BuildError>"));
    }

    #[test]
    fn build_error_present_with_three_variants() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub enum BuildError {"));
        assert!(out.contains("MissingField { kind: &'static str, field: &'static str },"));
        assert!(out.contains("UnexpectedKind { expected: &'static str, found: String },"));
        assert!(out.contains("InvalidUtf8(std::str::Utf8Error),"));
    }

    #[test]
    fn display_assembles_blocks_in_order() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = ra(&g, "g").to_string();
        let use_pos = out.find("use super::visitor::SourceNode;").unwrap();
        let pragma_pos = out.find("pub struct Pragma {").unwrap();
        let helpers_pos = out.find("pub fn child_by_field(").unwrap();
        let error_pos = out.find("pub enum BuildError {").unwrap();
        let struct_pos = out.find("pub struct A {").unwrap();
        assert!(use_pos < pragma_pos);
        assert!(pragma_pos < helpers_pos);
        assert!(helpers_pos < error_pos);
        assert!(error_pos < struct_pos);
    }

    // ── four-way field-type breakdown ───────────────────────────────────

    #[test]
    fn single_named_field_type_is_target_struct() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: Expr,"));
        assert!(out.contains(".child_by_field(\"value\")"));
    }

    #[test]
    fn single_anonymous_field_type_is_string() {
        let g = Grammar::from_rules([p(
            "decl",
            Field("value".into(), Box::new(TerminalLiteral("'+'".into()))),
        )]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: String,"));
        assert!(out.contains(".child_by_field(\"value\")"));
        assert!(out.contains(".text()?"));
        assert!(out.contains(".to_string();"));
    }

    #[test]
    fn multi_shape_field_type_is_generated_enum_name() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub value: Value,"));
        assert!(out.contains("pub enum Value {"));
        assert!(out.contains("Num(Num),"));
        assert!(out.contains("Str(Str),"));
    }

    #[test]
    #[should_panic(expected = "a field always resolves to at least one target kind")]
    fn field_rust_type_panics_on_empty_target() {
        field_rust_type(&AstFieldSpec::default(), &IndexMap::new());
    }

    #[test]
    #[should_panic(expected = "a field always resolves to at least one target kind")]
    fn field_try_from_panics_on_empty_target() {
        field_try_from("kind", "field", &AstFieldSpec::default());
    }

    // ── multi-shape enum naming (build_multi_shape_names) ───────────────

    #[test]
    fn build_multi_shape_names_shared_shape_reuses_one_enum() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p(
                "factor",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let names = build_multi_shape_names(&g).expect("no name collisions");
        assert_eq!(names.len(), 1, "one shape shared by both fields: {names:?}");
        assert_eq!(names.values().next().unwrap(), "Value");
    }

    #[test]
    fn build_multi_shape_names_differing_field_names_fall_back_to_shape_derived_name() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p(
                "factor",
                Field(
                    "operand".into(),
                    Box::new(Choice(vec![nt("num"), nt("str")])),
                ),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let names = build_multi_shape_names(&g).expect("no name collisions");
        assert_eq!(names.len(), 1);
        assert_eq!(names.values().next().unwrap(), "NumStr");
    }

    #[test]
    fn build_multi_shape_names_no_multi_shape_fields_returns_empty_map() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let names = build_multi_shape_names(&g).expect("no name collisions");
        assert!(names.is_empty());
    }

    #[test]
    fn build_multi_shape_names_synthesized_name_colliding_with_a_real_kind_is_an_error() {
        let g = Grammar::from_rules([
            p("Value", TerminalLiteral("'v'".into())),
            p(
                "x",
                Field("value".into(), Box::new(Choice(vec![nt("a"), nt("b")]))),
            ),
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
        ]);
        let err = build_multi_shape_names(&g).unwrap_err();
        assert!(err.contains("Value"), "error should name 'Value': {err}");
    }

    #[test]
    fn build_multi_shape_names_same_field_name_different_shapes_is_an_error() {
        let g = Grammar::from_rules([
            p(
                "x",
                Field("value".into(), Box::new(Choice(vec![nt("a"), nt("b")]))),
            ),
            p(
                "y",
                Field("value".into(), Box::new(Choice(vec![nt("c"), nt("d")]))),
            ),
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
            p("c", TerminalLiteral("'c'".into())),
            p("d", TerminalLiteral("'d'".into())),
        ]);
        let err = build_multi_shape_names(&g).unwrap_err();
        assert!(err.contains("shape [a, b]"), "{err}");
        assert!(err.contains("shape [c, d]"), "{err}");
    }

    // ── per-kind struct + TryFrom (fmt_struct_decl / fmt_struct_try_from) ─

    #[test]
    fn struct_multiple_field_uses_children_by_field_and_collect() {
        let g = Grammar::from_rules([
            p(
                "program",
                Field("items".into(), Box::new(ZeroOrMore(Box::new(nt("decl"))))),
            ),
            p("decl", TerminalLiteral("'d'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub items: Vec<Decl>,"));
        assert!(out.contains(".children_by_field(\"items\")"));
        assert!(out.contains(".collect::<Result<Vec<_>, _>>()?;"));
    }

    #[test]
    fn struct_leaf_kind_gets_text_field_and_text_call() {
        let g = Grammar::from_rules([p("num", TerminalPattern("/[0-9]+/".into()))]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Num {"));
        assert!(out.contains("pub text: String,"));
        assert!(out.contains("let text = node.text()?.to_string();"));
        assert!(out.contains("Ok(Num { pragma, text })"));
    }

    #[test]
    fn struct_single_field_uses_child_by_field_and_missing_field_error() {
        let g = Grammar::from_rules([
            p("decl", Field("value".into(), Box::new(nt("expr")))),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains(".child_by_field(\"value\")"));
        assert!(out.contains("BuildError::MissingField { kind: \"decl\", field: \"value\" }"));
    }

    // ── multi-shape enum dispatch (fmt_multi_shape_enum_try_from) ───────

    #[test]
    fn multi_shape_enum_dispatch_checks_is_named_when_token_variant_present() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field(
                    "value".into(),
                    Box::new(Choice(vec![nt("num"), TerminalLiteral("'+'".into())])),
                ),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("Token(String),"));
        assert!(out.contains("if !node.node.is_named() {"));
        assert!(out.contains("return Ok(Value::Token(node.text()?.to_string()));"));
    }

    #[test]
    fn multi_shape_enum_dispatch_omits_is_named_check_without_token_variant() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(!out.contains("is_named()"));
    }

    #[test]
    fn multi_shape_enum_dispatch_has_one_arm_per_kind_and_unexpected_kind_fallback() {
        let g = Grammar::from_rules([
            p(
                "term",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("\"num\" => Ok(Value::Num(node.try_into()?)),"));
        assert!(out.contains("\"str\" => Ok(Value::Str(node.try_into()?)),"));
        assert!(out.contains("found => Err(BuildError::UnexpectedKind {"));
        assert!(out.contains("expected: \"Value\","));
    }

    // ── Known v1 limitation: unlabeled top-level choice ─────────────────

    /// A non-leaf kind whose body is an unlabeled top-level choice among
    /// visible nonterminals derives a struct with *no* fields beyond
    /// `pragma` — deliberate (see "Known v1 limitation" in
    /// `plans/342.3.md`), not a panic or a warning. This test documents
    /// that as intentional, so it doesn't look like a regression later.
    #[test]
    fn known_v1_limitation_unlabeled_top_level_choice_yields_pragma_only_struct() {
        let g = Grammar::from_rules([
            p("statement", Choice(vec![nt("loop_stmt"), nt("if_stmt")])),
            p("loop_stmt", TerminalLiteral("'l'".into())),
            p("if_stmt", TerminalLiteral("'i'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("pub struct Statement {\n    pub pragma: Pragma,\n}"));
        assert!(out.contains("Ok(Statement { pragma,  })"));
    }

    // ── #[derive(Debug)] on every generated type ────────────────────────

    #[test]
    fn every_generated_type_derives_debug() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalPattern("/[0-9]+/".into())),
            p("str", TerminalPattern("/\"[^\"]*\"/".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("#[derive(Debug)]\npub struct Pragma {"));
        assert!(out.contains("#[derive(Debug)]\npub struct Decl {"));
        assert!(out.contains("#[derive(Debug)]\npub enum Value {"));
    }

    // ── independent kinds don't share a mechanically-copied impl ────────

    #[test]
    fn each_leaf_kind_gets_its_own_independent_try_from_impl() {
        let g = Grammar::from_rules([
            p("a", TerminalLiteral("'a'".into())),
            p("b", TerminalLiteral("'b'".into())),
        ]);
        let out = ra(&g, "g").to_string();
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for A {"));
        assert!(out.contains("impl<'tree> TryFrom<SourceNode<'tree>> for B {"));
        assert!(out.contains("Ok(A { pragma, text })"));
        assert!(out.contains("Ok(B { pragma, text })"));
    }
}
