# a comment
# <- @comment

expr -> term ;
# <- @variable.definition
#    ^^ @operator
#       ^^^^ @variable
#            ^ @punctuation.delimiter

rule -> 'literal' ;
#       ^^^^^^^^^ @string

rule -> /[a-z]+/ ;
#       ^^^^^^^^ @string.regexp

rule -> a | b ;
#       ^ @variable
#         ^ @operator
#           ^ @variable

rule -> (a | b)+ ;
#       ^ @punctuation.bracket
#             ^ @punctuation.bracket
#              ^ @operator

rule -> a+ ;
#        ^ @operator

rule -> b* ;
#        ^ @operator

rule -> c? ;
#        ^ @operator

rule -> << /[0-9]+/ >> ;
#       ^^ @punctuation.bracket
#                   ^^ @punctuation.bracket

rule -> lhs: expr ;
#       ^^^^ @label
#            ^^^^ @variable

rule -> (a b => name) ;
#       ^ @punctuation.bracket
#            ^^ @operator
#               ^^^^ @type
#                   ^ @punctuation.bracket

rule -> a b %prec.left 1 ;
#           ^ @operator
#            ^^^^^^^^^ @keyword.operator
#                      ^ @number

rule -> (a | b %prec 2) ;
#              ^ @operator
#               ^^^^ @keyword.operator
#                    ^ @number

%conflicts [expr, term]
# <- @keyword
#          ^ @punctuation.bracket
#                     ^ @punctuation.bracket

%conflicts [a, b], [c, d]
#          ^ @punctuation.bracket
#               ^ @punctuation.bracket
#                  ^ @punctuation.bracket
#                       ^ @punctuation.bracket
