/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DASH_GT = 1,
  anon_sym_SEMI = 2,
  anon_sym_PIPE = 3,
  sym_plus = 4,
  sym_asterisk = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  sym_pattern = 8,
  sym_literal = 9,
  sym_nonTerminal = 10,
  sym_grammar = 11,
  sym_rule = 12,
  sym_ruleBody = 13,
  sym_symbolSeq = 14,
  sym_symbol = 15,
  sym__kleeneOp = 16,
  sym_subSeq = 17,
  sym__terminal = 18,
  aux_sym_grammar_repeat1 = 19,
  aux_sym_ruleBody_repeat1 = 20,
  aux_sym_symbolSeq_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_SEMI] = ";",
  [anon_sym_PIPE] = "|",
  [sym_plus] = "plus",
  [sym_asterisk] = "asterisk",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_pattern] = "pattern",
  [sym_literal] = "literal",
  [sym_nonTerminal] = "nonTerminal",
  [sym_grammar] = "grammar",
  [sym_rule] = "rule",
  [sym_ruleBody] = "ruleBody",
  [sym_symbolSeq] = "symbolSeq",
  [sym_symbol] = "symbol",
  [sym__kleeneOp] = "_kleeneOp",
  [sym_subSeq] = "subSeq",
  [sym__terminal] = "_terminal",
  [aux_sym_grammar_repeat1] = "grammar_repeat1",
  [aux_sym_ruleBody_repeat1] = "ruleBody_repeat1",
  [aux_sym_symbolSeq_repeat1] = "symbolSeq_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_plus] = sym_plus,
  [sym_asterisk] = sym_asterisk,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_pattern] = sym_pattern,
  [sym_literal] = sym_literal,
  [sym_nonTerminal] = sym_nonTerminal,
  [sym_grammar] = sym_grammar,
  [sym_rule] = sym_rule,
  [sym_ruleBody] = sym_ruleBody,
  [sym_symbolSeq] = sym_symbolSeq,
  [sym_symbol] = sym_symbol,
  [sym__kleeneOp] = sym__kleeneOp,
  [sym_subSeq] = sym_subSeq,
  [sym__terminal] = sym__terminal,
  [aux_sym_grammar_repeat1] = aux_sym_grammar_repeat1,
  [aux_sym_ruleBody_repeat1] = aux_sym_ruleBody_repeat1,
  [aux_sym_symbolSeq_repeat1] = aux_sym_symbolSeq_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_nonTerminal] = {
    .visible = true,
    .named = true,
  },
  [sym_grammar] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_ruleBody] = {
    .visible = true,
    .named = true,
  },
  [sym_symbolSeq] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__kleeneOp] = {
    .visible = false,
    .named = true,
  },
  [sym_subSeq] = {
    .visible = true,
    .named = true,
  },
  [sym__terminal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_grammar_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ruleBody_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbolSeq_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\'', 9,
        '(', 17,
        ')', 18,
        '*', 16,
        '+', 15,
        '-', 7,
        '/', 8,
        ';', 13,
        '|', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(2);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(5);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_pattern);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_pattern);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_pattern);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '[') ADVANCE(3);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_pattern);
      if (lookahead == ']') ADVANCE(5);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_literal);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_literal);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_nonTerminal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_pattern] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_nonTerminal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_grammar] = STATE(18),
    [sym_rule] = STATE(10),
    [aux_sym_grammar_repeat1] = STATE(10),
    [sym_nonTerminal] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_LPAREN,
    STATE(2), 2,
      sym_symbol,
      aux_sym_symbolSeq_repeat1,
    STATE(6), 2,
      sym_subSeq,
      sym__terminal,
    ACTIONS(5), 3,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
    ACTIONS(10), 3,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [22] = 5,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(2), 2,
      sym_symbol,
      aux_sym_symbolSeq_repeat1,
    STATE(6), 2,
      sym_subSeq,
      sym__terminal,
    ACTIONS(13), 3,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
    ACTIONS(17), 3,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [44] = 6,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_symbolSeq,
    STATE(19), 1,
      sym_ruleBody,
    STATE(3), 2,
      sym_symbol,
      aux_sym_symbolSeq_repeat1,
    STATE(6), 2,
      sym_subSeq,
      sym__terminal,
    ACTIONS(17), 3,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [67] = 6,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_symbolSeq,
    STATE(20), 1,
      sym_ruleBody,
    STATE(3), 2,
      sym_symbol,
      aux_sym_symbolSeq_repeat1,
    STATE(6), 2,
      sym_subSeq,
      sym__terminal,
    ACTIONS(17), 3,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [90] = 3,
    STATE(9), 1,
      sym__kleeneOp,
    ACTIONS(21), 2,
      sym_plus,
      sym_asterisk,
    ACTIONS(19), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [107] = 5,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_symbolSeq,
    STATE(3), 2,
      sym_symbol,
      aux_sym_symbolSeq_repeat1,
    STATE(6), 2,
      sym_subSeq,
      sym__terminal,
    ACTIONS(17), 3,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [127] = 1,
    ACTIONS(23), 9,
      anon_sym_SEMI,
      anon_sym_PIPE,
      sym_plus,
      sym_asterisk,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [139] = 1,
    ACTIONS(25), 7,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_pattern,
      sym_literal,
      sym_nonTerminal,
  [149] = 3,
    ACTIONS(3), 1,
      sym_nonTerminal,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(11), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [160] = 3,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_nonTerminal,
    STATE(11), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [171] = 3,
    ACTIONS(36), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      aux_sym_ruleBody_repeat1,
    ACTIONS(34), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [182] = 3,
    ACTIONS(36), 1,
      anon_sym_PIPE,
    STATE(14), 1,
      aux_sym_ruleBody_repeat1,
    ACTIONS(38), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [193] = 3,
    ACTIONS(42), 1,
      anon_sym_PIPE,
    STATE(14), 1,
      aux_sym_ruleBody_repeat1,
    ACTIONS(40), 2,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [204] = 1,
    ACTIONS(40), 3,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [210] = 1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_nonTerminal,
  [215] = 1,
    ACTIONS(47), 1,
      anon_sym_DASH_GT,
  [219] = 1,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
  [223] = 1,
    ACTIONS(51), 1,
      anon_sym_SEMI,
  [227] = 1,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 67,
  [SMALL_STATE(6)] = 90,
  [SMALL_STATE(7)] = 107,
  [SMALL_STATE(8)] = 127,
  [SMALL_STATE(9)] = 139,
  [SMALL_STATE(10)] = 149,
  [SMALL_STATE(11)] = 160,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 182,
  [SMALL_STATE(14)] = 193,
  [SMALL_STATE(15)] = 204,
  [SMALL_STATE(16)] = 210,
  [SMALL_STATE(17)] = 215,
  [SMALL_STATE(18)] = 219,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 227,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_symbolSeq_repeat1, 2, 0, 0),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_symbolSeq_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [10] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_symbolSeq_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbolSeq, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subSeq, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruleBody, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruleBody, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ruleBody_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ruleBody_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bnf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bnf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
