/// Skeleton `highlights.scm` generator.
///
/// Applies naming-convention heuristics to assign Tree-sitter capture names
/// to grammar rules. Rules whose bodies contain no terminals are omitted;
/// unrecognised rules get a `; TODO: @???` placeholder unless `no_todos` is set.
use std::fmt;
use std::fmt::{Display, Formatter};

use super::nodes::GrammarNode;
use super::types::Grammar;

/// Returns `true` if `node` contains at least one terminal (literal or pattern).
fn has_terminal(node: &GrammarNode) -> bool {
    match node {
        GrammarNode::TerminalLiteral(_) | GrammarNode::TerminalPattern(_) => true,
        GrammarNode::Sequence(v) | GrammarNode::Choice(v) => v.iter().any(has_terminal),
        GrammarNode::Optional(b)
        | GrammarNode::ZeroOrMore(b)
        | GrammarNode::OneOrMore(b)
        | GrammarNode::Token(b)
        | GrammarNode::TokenImmediate(b) => has_terminal(b),
        GrammarNode::Field(_, b) | GrammarNode::Prec(_, _, b) => has_terminal(b),
        GrammarNode::Alias(b, _) => has_terminal(b),
        GrammarNode::NonTerminal(_) => false,
    }
}

/// Common keyword names shared across many programming languages.
const COMMON_KEYWORDS: &[&str] = &[
    "and",
    "as",
    "async",
    "await",
    "begin",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "def",
    "default",
    "delete",
    "do",
    "elif",
    "else",
    "elseif",
    "elsif",
    "end",
    "ensure",
    "except",
    "export",
    "extends",
    "finally",
    "fn",
    "for",
    "from",
    "func",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "match",
    "module",
    "new",
    "not",
    "of",
    "or",
    "raise",
    "rescue",
    "return",
    "static",
    "struct",
    "super",
    "switch",
    "then",
    "this",
    "throw",
    "try",
    "type",
    "typeof",
    "unless",
    "until",
    "use",
    "var",
    "when",
    "where",
    "while",
    "with",
    "yield",
];

/// Maps a rule name to a Tree-sitter capture name using naming-convention heuristics,
/// or returns `None` if no heuristic applies.
pub fn classify_rule(name: &str) -> Option<&'static str> {
    // Exact matches
    match name {
        "comment" => return Some("@comment"),
        "string" | "char" | "character" => return Some("@string"),
        "number" | "integer" | "float" | "decimal" => return Some("@number"),
        "identifier" | "name" => return Some("@variable"),
        "operator" => return Some("@operator"),
        "boolean" => return Some("@boolean"),
        "null" | "nil" | "none" | "undefined" | "void" => return Some("@constant.builtin"),
        _ => {}
    }

    // Prefix patterns
    if name.starts_with("keyword_") {
        return Some("@keyword");
    }

    // Suffix patterns
    if name.ends_with("_comment") {
        return Some("@comment");
    }
    if name.ends_with("_string") || name.starts_with("string_") {
        return Some("@string");
    }
    if name.ends_with("_literal") {
        return Some("@number");
    }
    if name.ends_with("_op") || name.ends_with("_operator") {
        return Some("@operator");
    }
    if name.ends_with("_identifier") || name.ends_with("_name") {
        return Some("@variable");
    }

    // Common keyword names
    if COMMON_KEYWORDS.contains(&name) {
        return Some("@keyword");
    }

    None
}

/// Generates a skeleton `highlights.scm` from a [`Grammar`].
pub struct Highlights<'a> {
    /// The grammar to generate highlights for.
    pub grammar: &'a Grammar,
    /// When `true`, omit `; TODO: @???` placeholder entries for unclassified rules.
    pub no_todos: bool,
}

impl Display for Highlights<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let version = env!("CARGO_PKG_VERSION");
        writeln!(f, "; Generated by ts-bnf-tool v{version} — edit as needed.")?;
        for production in self.grammar.productions.values() {
            if !has_terminal(&production.body) {
                continue;
            }
            match classify_rule(&production.name) {
                Some(capture) => writeln!(f, "({}) {capture}", production.name)?,
                None if !self.no_todos => writeln!(f, "; ({}) TODO: @???", production.name)?,
                None => {}
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn comment_exact() {
        assert_eq!(classify_rule("comment"), Some("@comment"));
    }

    #[test]
    fn comment_suffix() {
        assert_eq!(classify_rule("line_comment"), Some("@comment"));
        assert_eq!(classify_rule("block_comment"), Some("@comment"));
    }

    #[test]
    fn string_exact() {
        assert_eq!(classify_rule("string"), Some("@string"));
    }

    #[test]
    fn string_suffix_and_prefix() {
        assert_eq!(classify_rule("raw_string"), Some("@string"));
        assert_eq!(classify_rule("string_content"), Some("@string"));
    }

    #[test]
    fn number_exact() {
        assert_eq!(classify_rule("number"), Some("@number"));
        assert_eq!(classify_rule("integer"), Some("@number"));
        assert_eq!(classify_rule("float"), Some("@number"));
    }

    #[test]
    fn number_literal_suffix() {
        assert_eq!(classify_rule("hex_literal"), Some("@number"));
        assert_eq!(classify_rule("int_literal"), Some("@number"));
    }

    #[test]
    fn keyword_prefix() {
        assert_eq!(classify_rule("keyword_if"), Some("@keyword"));
        assert_eq!(classify_rule("keyword_return"), Some("@keyword"));
    }

    #[test]
    fn keyword_common_name() {
        assert_eq!(classify_rule("if"), Some("@keyword"));
        assert_eq!(classify_rule("return"), Some("@keyword"));
        assert_eq!(classify_rule("while"), Some("@keyword"));
    }

    #[test]
    fn operator_exact_and_suffix() {
        assert_eq!(classify_rule("operator"), Some("@operator"));
        assert_eq!(classify_rule("binary_op"), Some("@operator"));
        assert_eq!(classify_rule("unary_operator"), Some("@operator"));
    }

    #[test]
    fn identifier_exact_and_suffix() {
        assert_eq!(classify_rule("identifier"), Some("@variable"));
        assert_eq!(classify_rule("name"), Some("@variable"));
        assert_eq!(classify_rule("field_name"), Some("@variable"));
        assert_eq!(classify_rule("type_identifier"), Some("@variable"));
    }

    #[test]
    fn unknown_rule_returns_none() {
        assert_eq!(classify_rule("expr"), None);
        assert_eq!(classify_rule("declaration"), None);
        assert_eq!(classify_rule("statement"), None);
    }

    #[test]
    fn has_terminal_literal() {
        assert!(has_terminal(&GrammarNode::TerminalLiteral("'+'".into())));
    }

    #[test]
    fn has_terminal_pattern() {
        assert!(has_terminal(&GrammarNode::TerminalPattern(
            "/[0-9]+/".into()
        )));
    }

    #[test]
    fn has_terminal_nonterminal_only() {
        assert!(!has_terminal(&GrammarNode::NonTerminal("expr".into())));
    }

    #[test]
    fn has_terminal_sequence_mixed() {
        let node = GrammarNode::Sequence(vec![
            GrammarNode::NonTerminal("a".into()),
            GrammarNode::TerminalLiteral("'+'".into()),
        ]);
        assert!(has_terminal(&node));
    }

    #[test]
    fn has_terminal_sequence_pure_nonterminal() {
        let node = GrammarNode::Sequence(vec![
            GrammarNode::NonTerminal("a".into()),
            GrammarNode::NonTerminal("b".into()),
        ]);
        assert!(!has_terminal(&node));
    }

    #[test]
    fn has_terminal_nested_optional() {
        let node = GrammarNode::Optional(Box::new(GrammarNode::TerminalLiteral("';'".into())));
        assert!(has_terminal(&node));
    }
}
