use std::fmt;
use std::fmt::{Display, Formatter};

use crate::dom::NameOrLiteral;

use super::types::Grammar;

/// A wrapper that renders a [`Grammar`] as a complete `grammar.js` file.
pub struct Scaffold<'a> {
    /// The grammar to render.
    pub grammar: &'a Grammar,
    /// The grammar name passed to tree-sitter's `grammar({ name: … })`.
    pub name: &'a str,
    /// The source filename shown in the generated-file header (`<stdin>` for stdin).
    pub source: &'a str,
    /// When `true`, suppress the generated-file header comment.
    pub no_header: bool,
}

impl Scaffold<'_> {
    /// Emits the generated-file header comment, unless suppressed by `no_header`.
    fn fmt_header(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.no_header {
            let version = env!("CARGO_PKG_VERSION");
            writeln!(
                f,
                "// Generated by ts-bnf-tool v{version} from {} \u{2014} do not edit by hand.",
                self.source
            )?;
        }
        Ok(())
    }

    /// Emits the `word:` directive, if the grammar declares one.
    fn fmt_word(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if let Some(word) = &self.grammar.word {
            writeln!(f, "  word: $ => $.{},", word.name)?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `precedences:` directive, if the grammar declares any groups.
    fn fmt_precedences(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.precedences.is_empty() {
            writeln!(f, "  precedences: $ => [")?;
            for g in &self.grammar.precedences {
                let group_items = g
                    .items
                    .iter()
                    .map(|i| match i {
                        NameOrLiteral::Literal(x) => x.clone(),
                        NameOrLiteral::Name(n) => format!("$.{}", n.as_str()),
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(f, "    [{group_items}],")?;
            }
            writeln!(f, "  ],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `externals:` directive, if the grammar declares any.
    fn fmt_externals(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.externals.is_empty() {
            let items = self
                .grammar
                .externals
                .iter()
                .map(|item| match item {
                    NameOrLiteral::Literal(x) => x.clone(),
                    NameOrLiteral::Name(n) => format!("$.{}", n.as_str()),
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(f, "  externals: $ => [{items}],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `extras:` directive, if the grammar declares any.
    fn fmt_extras(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.extras.is_empty() {
            let items = self
                .grammar
                .extras
                .iter()
                .map(|item| {
                    if item.name.starts_with('/') {
                        item.name.clone()
                    } else {
                        format!("$.{}", item.name)
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(f, "  extras: $ => [{items}],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `inline:` directive, if the grammar declares any.
    fn fmt_inline(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.inline.is_empty() {
            let items = self
                .grammar
                .inline
                .iter()
                .map(|item| format!("$.{}", item.name))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(f, "  inline: $ => [{items}],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `supertypes:` directive, if the grammar declares any.
    fn fmt_supertypes(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.supertypes.is_empty() {
            let items = self
                .grammar
                .supertypes
                .iter()
                .map(|item| format!("$.{}", item.name))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(f, "  supertypes: $ => [{items}],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `conflicts:` directive, if the grammar declares any groups.
    fn fmt_conflicts(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.grammar.conflicts.is_empty() {
            writeln!(f, "  conflicts: $ => [")?;
            for group in &self.grammar.conflicts {
                let items = group
                    .rules
                    .iter()
                    .map(|n| format!("$.{n}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(f, "    [{items}],")?;
            }
            writeln!(f, "  ],")?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `rules:` block, with the root rule (per `%axiom` or source
    /// order) emitted first since tree-sitter treats the first entry as the
    /// start symbol.
    fn fmt_rules(&self, f: &mut Formatter<'_>) -> fmt::Result {
        writeln!(f, "  rules: {{")?;
        // tree-sitter treats the first entry in `rules:` as the start symbol,
        // so the root rule must be emitted first even when %axiom names a rule
        // that isn't first in source order; it is skipped in the loop below.
        let root = self.grammar.root_rule();
        if let Some(prod) = root.map(|name| &self.grammar.productions[name]) {
            writeln!(f, "    // {}:{}", prod.filename, prod.line)?;
            writeln!(f, "    {}: $ => {},", prod.name, prod.body)?;
        }
        for production in self.grammar.productions.values() {
            if root == Some(production.name.as_str()) {
                continue;
            }
            writeln!(f, "    // {}:{}", production.filename, production.line)?;
            writeln!(f, "    {}: $ => {},", production.name, production.body)?;
        }
        writeln!(f, "  }}")
    }
}

impl Display for Scaffold<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        self.fmt_header(f)?;
        writeln!(f, "module.exports = grammar({{")?;
        writeln!(f, "  name: \"{}\",", self.name)?;
        writeln!(f)?;
        self.fmt_word(f)?;
        self.fmt_precedences(f)?;
        self.fmt_externals(f)?;
        self.fmt_extras(f)?;
        self.fmt_inline(f)?;
        self.fmt_supertypes(f)?;
        self.fmt_conflicts(f)?;
        self.fmt_rules(f)?;
        write!(f, "}});")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dom::GrammarNode::TerminalLiteral;
    use crate::dom::test_utils::{cg, di, p, p_named};
    use crate::dom::{Grammar, GrammarNode};

    fn s<'a>(grammar: &'a Grammar, name: &'a str) -> Scaffold<'a> {
        Scaffold {
            grammar,
            name,
            source: "test.bnf",
            no_header: true,
        }
    }

    #[test]
    fn scaffold_single_rule() {
        let g = Grammar::from_rules([p("expr", TerminalLiteral("'x'".into()))]);
        assert_eq!(
            s(&g, "expr").to_string(),
            "module.exports = grammar({\n  name: \"expr\",\n\n  rules: {\n    // test.bnf:1\n    expr: $ => 'x',\n  }\n});"
        );
    }

    #[test]
    fn scaffold_source_comment_uses_production_filename() {
        let g = Grammar::from_rules([p_named(
            "expr",
            TerminalLiteral("'x'".into()),
            "grammar.bnf",
        )]);
        let out = Scaffold {
            grammar: &g,
            name: "g",
            source: "grammar.bnf",
            no_header: true,
        }
        .to_string();
        assert!(out.contains("    // grammar.bnf:1\n    expr: $ => 'x',"));
    }

    #[test]
    fn scaffold_source_comment_uses_stdin_placeholder() {
        let g = Grammar::from_rules([p_named("r", TerminalLiteral("'y'".into()), "<stdin>")]);
        let out = Scaffold {
            grammar: &g,
            name: "g",
            source: "<stdin>",
            no_header: true,
        }
        .to_string();
        assert!(out.contains("    // <stdin>:1"));
    }

    #[test]
    fn scaffold_multi_rule() {
        let g = Grammar::from_rules([
            p("a", TerminalLiteral("'x'".into())),
            p("b", GrammarNode::NonTerminal("a".into())),
        ]);
        let out = s(&g, "test").to_string();
        assert!(out.contains("    a: $ => 'x',"));
        assert!(out.contains("    b: $ => $.a,"));
        assert!(out.starts_with("module.exports = grammar({"));
        assert!(out.ends_with("});"));
    }

    #[test]
    fn scaffold_name_appears_in_output() {
        let g = Grammar::from_rules([p("r", TerminalLiteral("'y'".into()))]);
        let out = s(&g, "mygrammar").to_string();
        assert!(out.contains("name: \"mygrammar\""));
    }

    #[test]
    fn scaffold_no_conflicts_omits_key() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = s(&g, "g").to_string();
        assert!(!out.contains("conflicts"));
    }

    #[test]
    fn scaffold_with_single_conflict_group() {
        let mut g = Grammar::from_rules([p("expr", TerminalLiteral("'x'".into()))]);
        g.conflicts = vec![cg(&["expr", "term"], 0)];
        let out = s(&g, "g").to_string();
        assert!(out.contains("  conflicts: $ => ["));
        assert!(out.contains("    [$.expr, $.term],"));
        assert!(out.contains("  ],"));
        assert!(out.find("conflicts").unwrap() < out.find("rules").unwrap());
    }

    #[test]
    fn scaffold_with_multiple_conflict_groups() {
        let mut g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        g.conflicts = vec![cg(&["a", "b"], 0), cg(&["c", "d", "e"], 0)];
        let out = s(&g, "g").to_string();
        assert!(out.contains("    [$.a, $.b],"));
        assert!(out.contains("    [$.c, $.d, $.e],"));
    }

    #[test]
    fn scaffold_with_supertypes() {
        let mut g = Grammar::from_rules([p("expression", TerminalLiteral("'x'".into()))]);
        g.supertypes = vec![di("expression", 0), di("statement", 0)];
        let out = s(&g, "g").to_string();
        assert!(out.contains("  supertypes: $ => [$.expression, $.statement],"));
        assert!(out.find("supertypes").unwrap() < out.find("rules").unwrap());
    }

    #[test]
    fn scaffold_no_supertypes_omits_key() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = s(&g, "g").to_string();
        assert!(!out.contains("supertypes"));
    }

    #[test]
    fn scaffold_with_extras_pattern_and_rule() {
        let mut g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        g.extras = vec![di("/\\s/", 0), di("comment", 0)];
        let out = s(&g, "g").to_string();
        assert!(out.contains("  extras: $ => [/\\s/, $.comment],"));
        assert!(out.find("extras").unwrap() < out.find("rules").unwrap());
    }

    #[test]
    fn scaffold_no_extras_omits_key() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = s(&g, "g").to_string();
        assert!(!out.contains("extras"));
    }

    // ── precedences ──────────────────────────────────────────────────────────

    #[test]
    fn scaffold_no_precedences_omits_key() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = s(&g, "g").to_string();
        assert!(!out.contains("precedences"));
    }

    #[test]
    fn scaffold_with_precedence_groups_name_and_literal() {
        use crate::dom::NameOrLiteral;
        use crate::dom::test_utils::pg;
        let mut g = Grammar::from_rules([p("expr", TerminalLiteral("'x'".into()))]);
        g.precedences = vec![
            pg(
                &[
                    NameOrLiteral::Name("expr".into()),
                    NameOrLiteral::Literal("'call'".into()),
                ],
                0,
            ),
            pg(&[NameOrLiteral::Name("term".into())], 0),
        ];
        let out = s(&g, "g").to_string();
        assert!(out.contains("  precedences: $ => ["));
        assert!(out.contains("    [$.expr, 'call'],"));
        assert!(out.contains("    [$.term],"));
        assert!(out.contains("  ],"));
    }

    #[test]
    fn scaffold_precedences_before_extras() {
        use crate::dom::NameOrLiteral;
        use crate::dom::test_utils::{di, pg};
        let mut g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        g.precedences = vec![pg(&[NameOrLiteral::Name("a".into())], 0)];
        g.extras = vec![di("/\\s/", 0)];
        let out = s(&g, "g").to_string();
        assert!(out.find("precedences").unwrap() < out.find("extras").unwrap());
    }

    // ── externals ────────────────────────────────────────────────────────────

    #[test]
    fn scaffold_no_externals_omits_key() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = s(&g, "g").to_string();
        assert!(!out.contains("externals"));
    }

    #[test]
    fn scaffold_with_externals_name_and_literal() {
        let mut g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        g.externals = vec![
            NameOrLiteral::Name("tok".into()),
            NameOrLiteral::Literal("'lit'".into()),
        ];
        let out = s(&g, "g").to_string();
        assert!(out.contains("  externals: $ => [$.tok, 'lit'],"));
    }

    #[test]
    fn scaffold_externals_before_extras() {
        let mut g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        g.externals = vec![NameOrLiteral::Name("tok".into())];
        g.extras = vec![di("/\\s/", 0)];
        let out = s(&g, "g").to_string();
        assert!(out.find("externals").unwrap() < out.find("extras").unwrap());
    }

    #[test]
    fn scaffold_header_present_by_default() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = Scaffold {
            grammar: &g,
            name: "g",
            source: "grammar.bnf",
            no_header: false,
        }
        .to_string();
        let version = env!("CARGO_PKG_VERSION");
        assert!(out.starts_with(&format!(
            "// Generated by ts-bnf-tool v{version} from grammar.bnf \u{2014} do not edit by hand.\n"
        )));
        assert!(out.contains("module.exports = grammar({"));
    }

    #[test]
    fn scaffold_axiom_rule_emitted_first() {
        let mut g = Grammar::from_rules([
            p("a", TerminalLiteral("'x'".into())),
            p("b", TerminalLiteral("'y'".into())),
        ]);
        g.declare_axiom(di("b", 1));
        let out = s(&g, "g").to_string();
        assert!(out.find("b: $ =>").unwrap() < out.find("a: $ =>").unwrap());
    }

    #[test]
    fn scaffold_axiom_rule_not_duplicated() {
        let mut g = Grammar::from_rules([
            p("a", TerminalLiteral("'x'".into())),
            p("b", TerminalLiteral("'y'".into())),
        ]);
        g.declare_axiom(di("b", 1));
        let out = s(&g, "g").to_string();
        assert_eq!(out.matches("b: $ =>").count(), 1);
    }

    #[test]
    fn scaffold_no_axiom_preserves_declaration_order() {
        let g = Grammar::from_rules([
            p("a", TerminalLiteral("'x'".into())),
            p("b", TerminalLiteral("'y'".into())),
        ]);
        let out = s(&g, "g").to_string();
        assert!(out.find("a: $ =>").unwrap() < out.find("b: $ =>").unwrap());
    }

    #[test]
    fn scaffold_no_header_suppresses_comment() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = Scaffold {
            grammar: &g,
            name: "g",
            source: "grammar.bnf",
            no_header: true,
        }
        .to_string();
        assert!(!out.contains("Generated by"));
        assert!(out.starts_with("module.exports = grammar({"));
    }

    #[test]
    fn scaffold_header_uses_stdin_source() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = Scaffold {
            grammar: &g,
            name: "g",
            source: "<stdin>",
            no_header: false,
        }
        .to_string();
        assert!(out.contains("from <stdin>"));
    }

    #[test]
    fn scaffold_word_directive_emitted_before_extras() {
        let mut g = Grammar::from_rules([p("ident", TerminalLiteral("'x'".into()))]);
        g.declare_word(di("ident", 1));
        g.extras = vec![di("/\\s/", 0)];
        let out = s(&g, "g").to_string();
        assert!(
            out.contains("  word: $ => $.ident,"),
            "word key must appear"
        );
        assert!(
            out.find("word:").unwrap() < out.find("extras:").unwrap(),
            "word must come before extras"
        );
    }

    #[test]
    fn scaffold_word_directive_omitted_when_absent() {
        let g = Grammar::from_rules([p("ident", TerminalLiteral("'x'".into()))]);
        assert!(!s(&g, "g").to_string().contains("word:"));
    }
}
