use std::fmt;
use std::fmt::{Display, Formatter};

use indoc::{formatdoc, indoc};

use super::super::types::Grammar;
use super::markdown::render_table;
use super::text::{indent, prefix_lines};
use super::{
    body_for_kind, check_visitor, collect_anonymous_children, collect_fields, is_leaf_body,
    to_snake_case, visible_kinds,
};

/// A wrapper that renders a [`Grammar`]'s derived visitor shape (see the
/// parent [`super`] module) as a complete Rust source file containing an
/// ANTLR-style `Visitor<'tree>` trait — one `visit_<kind>` method per
/// visible node kind, plus a `visit()` dispatcher and a `combine`-based fold.
///
/// Mirrors [`super::super::Scaffold`]'s shape: a reference to the grammar
/// plus the same header-comment fields, so the two emitters read the same
/// way even though one renders `grammar.js` and the other a Rust trait.
///
/// Only buildable via [`RustVisitor::new`], not as a struct literal: that
/// constructor runs [`check_visitor`] before a `RustVisitor` can exist at
/// all, so a grammar whose kinds would collide into the same `visit_*`
/// method name is rejected there — with a clear diagnostic naming both
/// offending kinds — rather than silently rendered into Rust source with
/// two same-named method definitions that only fails later, at `rustc` time,
/// in whatever downstream build happens to compile the generated file.
pub struct RustVisitor<'a> {
    /// The grammar to derive the trait from.
    grammar: &'a Grammar,
    /// The grammar's name, used in the generated trait's doc comment (e.g.
    /// "ANTLR-style visitor for the `decls` tree-sitter grammar.").
    name: &'a str,
    /// The source filename shown in the generated-file header (`<stdin>` for stdin).
    source: &'a str,
    /// When `true`, suppress the generated-file header comment.
    no_header: bool,
}

impl<'a> RustVisitor<'a> {
    /// Builds a `RustVisitor` for `grammar`, or an `Err` naming the
    /// colliding kinds if [`check_visitor`] rejects it.
    ///
    /// This is the only way to construct a `RustVisitor` — see the type's
    /// own doc comment for why the check can't be skipped by construction.
    ///
    /// - `name`: the grammar's name, used in the generated trait's doc
    ///   comment.
    /// - `source`: the source filename shown in the generated-file header
    ///   (`<stdin>` for stdin).
    /// - `no_header`: when `true`, suppresses the generated-file header
    ///   comment.
    pub fn new(
        grammar: &'a Grammar,
        name: &'a str,
        source: &'a str,
        no_header: bool,
    ) -> Result<Self, String> {
        check_visitor(grammar)?;
        Ok(Self {
            grammar,
            name,
            source,
            no_header,
        })
    }
}

impl RustVisitor<'_> {
    /// Emits the generated-file header comment, unless suppressed by
    /// `no_header` — identical wording to [`super::super::Scaffold`]'s, since
    /// this is also generated code that shouldn't be hand-edited. Unlike
    /// `Scaffold::fmt_header`, a blank line follows the comment: the next
    /// thing emitted is a Rust `use` statement, and comment-blank-`use` reads
    /// more naturally than comment-immediately-`use`.
    fn fmt_header(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if !self.no_header {
            let version = env!("CARGO_PKG_VERSION");
            writeln!(
                f,
                "// Generated by ts-bnf-tool v{version} from {} \u{2014} do not edit by hand.",
                self.source
            )?;
            writeln!(f)?;
        }
        Ok(())
    }

    /// Emits the `use` import, the `Visitor<'tree>` trait's own doc comment
    /// (ANTLR correspondence table, `combine`-pattern table, minimal
    /// example), and the trait's opening line.
    ///
    /// This is the doc a reader sees when they open the generated file and
    /// look at `Visitor`'s definition — since they won't have read the
    /// design rationale behind it, it has to stand alone: what ANTLR concept
    /// each method corresponds to, what `combine` is supposed to do for a
    /// few common `Output` shapes, and one small worked-through
    /// implementation. One `formatdoc!` block, rather than a `writeln!` per
    /// line, since this is fixed text with a single interpolated value (the
    /// grammar `name`) — same choice `main.rs` makes for its own
    /// multi-line generated-file content.
    fn fmt_trait_doc(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let name = self.name;
        let antlr_table = prefix_lines(
            &render_table(&[
                ["ANTLR (`AbstractParseTreeVisitor`)", "Here"],
                ["`visit(tree)`", "[`Visitor::visit`]"],
                ["`visitChildren(node)`", "[`Visitor::children_visitor`]"],
                [
                    "`aggregateResult(agg, next)`",
                    "[`Visitor::combine`] (`Vec`-based, not pairwise)",
                ],
                [
                    "`defaultResult()`",
                    "[`Visitor::default_result`] (`= combine(vec![])`)",
                ],
                ["`visitErrorNode(node)`", "[`Visitor::error_visitor`]"],
                [
                    "(no ANTLR analogue)",
                    "[`Visitor::missing_visitor`], for tree-sitter's `MISSING` nodes",
                ],
            ]),
            "///",
        );
        let combine_table = prefix_lines(
            &render_table(&[
                ["Output type", "Typical `combine` body"],
                ["`()` (side-effect)", "`Ok(())`"],
                [
                    "`Vec<T>` (collect)",
                    "`Ok(results.into_iter().flatten().collect())`",
                ],
                [
                    "`Option<T>` (find-first)",
                    "`Ok(results.into_iter().flatten().next())`",
                ],
            ]),
            "///",
        );
        write!(
            f,
            "{}",
            formatdoc! {r#"
                use tree_sitter::Node;

                /// ANTLR-style visitor for the `{name}` tree-sitter grammar.
                ///
                /// ## How to implement
                ///
                /// Implement [`Visitor::combine`], folding a `Vec` of child outputs into
                /// one output, and override whichever `visit_<kind>` methods you care
                /// about. Every method you don't override falls back to a sensible
                /// default: non-leaf kinds recurse via [`Visitor::children_visitor`], leaf
                /// kinds return [`Visitor::default_result`].
                ///
                /// ## ANTLR correspondence
                ///
                {antlr_table}
                ///
                /// ## `combine` patterns
                ///
                {combine_table}
                ///
                /// ## Minimal example
                ///
                /// ```ignore
                /// struct Counter(usize);
                ///
                /// impl<'t> Visitor<'t> for Counter {{
                ///     type Output = ();
                ///     type Error = std::convert::Infallible;
                ///
                ///     fn combine(&mut self, _: Vec<()>) -> Result<(), Self::Error> {{
                ///         Ok(())
                ///     }}
                ///
                ///     fn visit_decl(&mut self, node: Node<'t>) -> Result<(), Self::Error> {{
                ///         self.0 += 1;
                ///         self.children_visitor(node)
                ///     }}
                /// }}
                /// ```
                pub trait Visitor<'tree> {{
            "#}
        )
    }

    /// Emits the trait's two associated types, the required `combine`
    /// method, and the five ANTLR-mirroring helpers with their default
    /// bodies (`children_visitor`, `field_visitor`, `default_result`,
    /// `error_visitor`, `missing_visitor` — see [`RustVisitor::fmt_trait_doc`]'s
    /// ANTLR correspondence table for what each one maps to).
    ///
    /// Every kind-derived `visit_<kind>` method is exactly `visit_<kind>`,
    /// and none of these five helpers start with `visit_` (they use a
    /// `_visitor` suffix instead) — so a kind name can never collide with
    /// one of them; [`super::check_method_name_collisions`] only has to
    /// guard against kind/kind collisions, not kind/helper ones.
    ///
    /// Each member is written flush-left here (readable to write and
    /// review), `trim_end`-ed to drop indoc's own trailing newline, joined
    /// with a blank line between members, and indented one level in a
    /// single pass via [`indent`] — hand-typing the leading spaces into
    /// every source line is exactly what produced the markdown-table test
    /// failure earlier, so a single programmatic indent pass replaces that
    /// everywhere in this file.
    fn fmt_core_members(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let members = [
            indoc! {r#"
                /// The value produced by each `visit_*` call.
                type Output;

                /// The error type. Use `std::convert::Infallible` for a
                /// visitor that can't fail.
                type Error;
            "#},
            indoc! {r#"
                /// Merges child outputs into a single output.
                ///
                /// This is the only method you *must* implement. Called by
                /// [`Visitor::children_visitor`] and [`Visitor::field_visitor`]
                /// with one [`Visitor::Output`] per visited child, and by
                /// [`Visitor::default_result`] with an empty `Vec`.
                fn combine(&mut self, results: Vec<Self::Output>) -> Result<Self::Output, Self::Error>;
            "#},
            indoc! {r#"
                /// Walks all named children of `node` and combines their outputs.
                ///
                /// This is the default body of every non-leaf `visit_*`
                /// method. Anonymous children (punctuation, keywords) are
                /// silently skipped.
                fn children_visitor(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {
                    let mut cursor = node.walk();
                    let mut results = Vec::new();
                    for child in node.named_children(&mut cursor) {
                        results.push(self.visit(child)?);
                    }
                    self.combine(results)
                }
            "#},
            indoc! {r#"
                /// Visits every child in field `field_name` and combines
                /// their outputs.
                ///
                /// Handles `multiple: true` fields correctly, visiting
                /// every match rather than just the first. Returns
                /// [`Visitor::default_result`] when the field is absent.
                fn field_visitor(
                    &mut self,
                    node: Node<'tree>,
                    field_name: &str,
                ) -> Result<Self::Output, Self::Error> {
                    let mut cursor = node.walk();
                    let mut results = Vec::new();
                    for child in node.children_by_field_name(field_name, &mut cursor) {
                        results.push(self.visit(child)?);
                    }
                    self.combine(results)
                }
            "#},
            indoc! {r#"
                /// The neutral output, `combine(vec![])`.
                ///
                /// ANTLR's `defaultResult()`. Return this from a leaf's
                /// `visit_*` method, or from any override meaning: handled,
                /// do not recurse.
                fn default_result(&mut self) -> Result<Self::Output, Self::Error> {
                    self.combine(vec![])
                }
            "#},
            indoc! {r#"
                /// Visits an `ERROR` node, one of tree-sitter's
                /// parse-recovery nodes.
                ///
                /// ANTLR's `visitErrorNode`. Defaults to recursing into its
                /// children.
                fn error_visitor(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {
                    self.children_visitor(node)
                }
            "#},
            indoc! {r#"
                /// Visits a `MISSING` node, tree-sitter's zero-width
                /// parse-recovery marker.
                ///
                /// [`Node::kind`] reports the *expected* kind on a `MISSING`
                /// node, not a distinct missing kind, so [`Visitor::visit`]
                /// checks [`Node::is_missing`] before kind dispatch and
                /// routes here instead. Defaults to
                /// [`Visitor::default_result`]: treated as absent, not
                /// recursed into.
                fn missing_visitor(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {
                    let _ = node;
                    self.default_result()
                }
            "#},
        ];
        let body = members
            .iter()
            .map(|m| m.trim_end())
            .collect::<Vec<_>>()
            .join("\n\n");
        writeln!(f, "{}", indent(&body, 4))
    }

    /// Emits the `visit()` dispatcher.
    ///
    /// [`Node::is_missing`] is checked before kind dispatch: `node.kind()`
    /// alone can't distinguish a `MISSING` node from an ordinary one of
    /// whatever kind the parser expected there, so a `MISSING` node always
    /// routes to `missing_visitor` regardless of what kind it reports.
    /// `"ERROR"` routes to `error_visitor`; every other kind not explicitly
    /// listed (anonymous tokens, kinds this grammar doesn't produce) falls
    /// through to `children_visitor`.
    ///
    /// One match arm per visible kind derived from the grammar (per
    /// [`visible_kinds`]), in the same order, each calling that kind's
    /// `visit_<kind>` method (per [`to_snake_case`]) — those per-kind
    /// methods are emitted by [`RustVisitor::fmt_visit_methods`].
    fn fmt_dispatcher(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let arms = visible_kinds(self.grammar)
            .iter()
            .map(|kind| {
                let method = to_snake_case(kind);
                format!("        \"{kind}\" => self.visit_{method}(node),")
            })
            .collect::<Vec<_>>()
            .join("\n");
        let body = formatdoc! {r#"
            /// Dispatches `node` to the appropriate `visit_<kind>` method
            /// based on its kind.
            ///
            /// [`Node::is_missing`] is checked first: `node.kind()` alone
            /// can't distinguish a `MISSING` node from an ordinary one of
            /// whatever kind the parser expected there, so a `MISSING`
            /// node always routes to [`Visitor::missing_visitor`]
            /// regardless of what kind it reports.
            fn visit(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {{
                if node.is_missing() {{
                    return self.missing_visitor(node);
                }}
                match node.kind() {{
            {arms}
                    "ERROR" => self.error_visitor(node),
                    _ => self.children_visitor(node),
                }}
            }}
        "#};
        writeln!(f, "\n{}", indent(body.trim_end(), 4))
    }

    /// Emits one documented `visit_<kind>` method per visible kind, each
    /// built by [`RustVisitor::fmt_visit_method`] and joined with a blank
    /// line between methods.
    fn fmt_visit_methods(&self, f: &mut Formatter<'_>) -> fmt::Result {
        let methods = visible_kinds(self.grammar)
            .iter()
            .map(|kind| self.fmt_visit_method(kind))
            .collect::<Vec<_>>()
            .join("\n\n");
        if methods.is_empty() {
            return Ok(());
        }
        writeln!(f, "\n{}", indent(&methods, 4))
    }

    /// Builds one `visit_<kind>` method's flush-left text: a doc comment
    /// listing `kind`'s resolved fields ([`collect_fields`]) and any
    /// anonymous children ([`collect_anonymous_children`]), followed by the
    /// method signature and a default body — [`Visitor::default_result`]
    /// for a leaf kind ([`is_leaf_body`]), [`Visitor::children_visitor`]
    /// otherwise.
    ///
    /// `body_for_kind(self.grammar, kind)` is expected to resolve for every
    /// `kind` this is called with: every caller sources `kind` from
    /// [`visible_kinds`], and [`body_for_kind`] is guaranteed to resolve
    /// every kind that function produces (see its own doc).
    fn fmt_visit_method(&self, kind: &str) -> String {
        let body =
            body_for_kind(self.grammar, kind).expect("every visible kind has a resolvable body");
        let method_name = to_snake_case(kind);
        let leaf = is_leaf_body(self.grammar, body);
        let fields = collect_fields(self.grammar, body);
        let anonymous = collect_anonymous_children(self.grammar, body);

        let mut doc = format!("Visits a `{kind}` node.\n");
        if !fields.is_empty() {
            doc.push_str("\n**Fields:**\n");
            for (field_name, target) in &fields {
                let mut options: Vec<String> = target
                    .named
                    .iter()
                    .map(|k| format!("`{k}` ([`Visitor::visit_{}`])", to_snake_case(k)))
                    .collect();
                if target.anonymous_token {
                    options.push("an anonymous token".to_string());
                }
                doc.push_str(&format!(
                    "- `{field_name}` -> {}, via `self.field_visitor(node, \"{field_name}\")`\n",
                    options.join(" | ")
                ));
            }
        }
        if !anonymous.is_empty() {
            let tokens = anonymous
                .iter()
                .map(|t| format!("`{t}`"))
                .collect::<Vec<_>>()
                .join(", ");
            doc.push_str(&format!(
                "\n**Anonymous children** (not visited by default): {tokens}\n"
            ));
        }
        if leaf {
            doc.push_str(
                "\n**Leaf node**: no visible children; defaults to [`Visitor::default_result`].\n",
            );
        }

        let doc_comment = prefix_lines(doc.trim_end(), "///");
        // A leaf's default body never touches `node` — same situation
        // `missing_visitor` has, fixed the same way:
        // `let _ = node;` suppresses the unused-variable warning without
        // renaming the parameter to `_node`, so it reads the same as every
        // other method here and an override can still just use `node`.
        let default_body = if leaf {
            "let _ = node;\n    self.default_result()"
        } else {
            "self.children_visitor(node)"
        };
        format!(
            "{doc_comment}\nfn visit_{method_name}(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {{\n    {default_body}\n}}"
        )
    }
}

impl Display for RustVisitor<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        self.fmt_header(f)?;
        self.fmt_trait_doc(f)?;
        self.fmt_core_members(f)?;
        self.fmt_dispatcher(f)?;
        self.fmt_visit_methods(f)?;
        writeln!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dom::GrammarNode::{Alias, Choice, Field, Sequence, TerminalLiteral};
    use crate::dom::test_utils::{nt, p};

    fn rv<'a>(grammar: &'a Grammar, name: &'a str) -> RustVisitor<'a> {
        RustVisitor::new(grammar, name, "test.bnf", true).expect("grammar must be visitor-safe")
    }

    #[test]
    fn header_present_by_default() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = RustVisitor::new(&g, "g", "grammar.bnf", false)
            .expect("grammar must be visitor-safe")
            .to_string();
        let version = env!("CARGO_PKG_VERSION");
        assert!(out.starts_with(&format!(
            "// Generated by ts-bnf-tool v{version} from grammar.bnf \u{2014} do not edit by hand.\n"
        )));
    }

    #[test]
    fn header_no_header_suppresses_comment() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(!out.contains("Generated by"));
        assert!(out.starts_with("use tree_sitter::Node;"));
    }

    #[test]
    fn trait_doc_names_the_grammar() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "mygrammar").to_string();
        assert!(out.contains("ANTLR-style visitor for the `mygrammar` tree-sitter grammar."));
    }

    #[test]
    fn trait_doc_includes_antlr_correspondence_table() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("## ANTLR correspondence"));
        assert!(out.contains("/// | `visit(tree)`"));
        assert!(out.contains("[`Visitor::children_visitor`]"));
        assert!(out.contains("[`Visitor::error_visitor`]"));
        assert!(out.contains("[`Visitor::missing_visitor`]"));
    }

    #[test]
    fn trait_doc_includes_combine_patterns_table() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("## `combine` patterns"));
        assert!(out.contains("`Ok(results.into_iter().flatten().collect())`"));
    }

    #[test]
    fn trait_doc_includes_minimal_example() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("## Minimal example"));
        assert!(out.contains("impl<'t> Visitor<'t> for Counter {"));
        assert!(out.contains("self.children_visitor(node)"));
    }

    #[test]
    fn trait_doc_lines_are_all_doc_comments() {
        // Every line between the `use` statement and the trait's opening
        // line (i.e. the trait's own doc comment, not its body) must start
        // with `///` — a stray un-prefixed line would leak out of the doc
        // comment and break the generated file.
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        let body = out
            .strip_prefix("use tree_sitter::Node;\n\n")
            .expect("output starts with the use statement");
        let doc_comment = body
            .split_once("pub trait Visitor<'tree> {")
            .expect("output contains the trait's opening line")
            .0;
        for line in doc_comment.lines() {
            assert!(line.starts_with("///"), "non-doc-comment line: {line:?}");
        }
    }

    #[test]
    fn output_opens_and_closes_the_trait() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("pub trait Visitor<'tree> {"));
        assert!(out.trim_end().ends_with('}'));
    }

    // ── fmt_core_members ────────────────────────────────────────────────

    #[test]
    fn core_members_include_associated_types() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("    type Output;"));
        assert!(out.contains("    type Error;"));
    }

    #[test]
    fn core_members_include_combine_with_no_default_body() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains(
            "    fn combine(&mut self, results: Vec<Self::Output>) -> Result<Self::Output, Self::Error>;"
        ));
    }

    #[test]
    fn core_members_include_all_five_helpers() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        for helper in [
            "fn children_visitor(&mut self, node: Node<'tree>)",
            "fn field_visitor(",
            "fn default_result(&mut self)",
            "fn error_visitor(&mut self, node: Node<'tree>)",
            "fn missing_visitor(&mut self, node: Node<'tree>)",
        ] {
            assert!(out.contains(helper), "missing helper signature: {helper}");
        }
    }

    #[test]
    fn core_members_default_bodies_call_combine_or_children_visitor() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("self.combine(results)"));
        assert!(out.contains("self.combine(vec![])"));
        assert!(out.contains("self.children_visitor(node)"));
        assert!(out.contains("self.default_result()"));
    }

    #[test]
    fn core_members_are_indented_one_level() {
        // Every member lives inside `pub trait Visitor<'tree> { … }`, so
        // none of its lines should be flush against the file's left margin.
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        let members = out
            .split_once("pub trait Visitor<'tree> {\n")
            .expect("output contains the trait's opening line")
            .1;
        for line in members.lines() {
            if line.is_empty() || line == "}" {
                continue;
            }
            assert!(line.starts_with("    "), "not indented: {line:?}");
        }
    }

    #[test]
    fn core_members_appear_after_the_trait_doc() {
        // The trait doc's own minimal example also contains a `fn combine(`
        // line (as a `///`-commented illustration), so this looks for the
        // real, unindented-by-`///`, semicolon-terminated signature —
        // otherwise the example's occurrence (which comes first) would make
        // this pass even if the real member landed in the wrong place.
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        let trait_open = out.find("pub trait Visitor<'tree> {").unwrap();
        let combine_pos = out
            .find("    fn combine(&mut self, results: Vec<Self::Output>) -> Result<Self::Output, Self::Error>;")
            .unwrap();
        assert!(trait_open < combine_pos);
    }

    // ── fmt_dispatcher ───────────────────────────────────────────────────

    #[test]
    fn dispatcher_checks_is_missing_first() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains(
            "fn visit(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {"
        ));
        let visit_pos = out.find("fn visit(&mut self,").unwrap();
        let is_missing_pos = out.find("if node.is_missing()").unwrap();
        let match_pos = out.find("match node.kind()").unwrap();
        assert!(visit_pos < is_missing_pos);
        assert!(is_missing_pos < match_pos);
        assert!(out.contains("return self.missing_visitor(node);"));
    }

    #[test]
    fn dispatcher_has_one_arm_per_visible_kind_in_order() {
        let g = Grammar::from_rules([
            p("program", TerminalLiteral("'x'".into())),
            p("decl", nt("program")),
        ]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("\"program\" => self.visit_program(node),"));
        assert!(out.contains("\"decl\" => self.visit_decl(node),"));
        let program_pos = out
            .find("\"program\" => self.visit_program(node),")
            .unwrap();
        let decl_pos = out.find("\"decl\" => self.visit_decl(node),").unwrap();
        assert!(program_pos < decl_pos);
    }

    #[test]
    fn dispatcher_arms_are_indented_two_levels() {
        // Match arms sit inside `match node.kind() { ... }`, itself inside
        // `fn visit(...) { ... }`, itself inside the trait body — three
        // nesting levels, so 8 spaces, not the 4 that'd be enough for a
        // top-level trait member. `core_members_are_indented_one_level`
        // only checks "at least 4 spaces" across the whole body, which
        // would trivially pass even at the wrong (4-space) depth, so this
        // checks the arm lines specifically.
        let g = Grammar::from_rules([p("program", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("        \"program\" => self.visit_program(node),"));
        assert!(!out.contains("\n    \"program\" => self.visit_program(node),"));
    }

    #[test]
    fn dispatcher_excludes_hidden_and_inline_rules() {
        let mut g = Grammar::from_rules([
            p("visible", TerminalLiteral("'x'".into())),
            p("_hidden", TerminalLiteral("'y'".into())),
            p("helper", TerminalLiteral("'z'".into())),
        ]);
        g.inline = vec![crate::dom::test_utils::di("helper", 0)];
        let out = rv(&g, "g").to_string();
        assert!(out.contains("\"visible\" => self.visit_visible(node),"));
        assert!(!out.contains("visit__hidden"));
        assert!(!out.contains("visit_helper"));
    }

    #[test]
    fn dispatcher_error_and_fallback_arms() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("\"ERROR\" => self.error_visitor(node),"));
        assert!(out.contains("_ => self.children_visitor(node),"));
    }

    #[test]
    fn dispatcher_appears_after_core_members() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        let missing_visitor_pos = out.find("fn missing_visitor(").unwrap();
        let visit_pos = out.find("fn visit(&mut self,").unwrap();
        assert!(missing_visitor_pos < visit_pos);
    }

    // ── fmt_visit_methods / fmt_visit_method ────────────────────────────

    #[test]
    fn visit_methods_appear_after_the_dispatcher() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        let visit_pos = out.find("fn visit(&mut self,").unwrap();
        let visit_a_pos = out.find("fn visit_a(").unwrap();
        assert!(visit_pos < visit_a_pos);
    }

    #[test]
    fn visit_method_is_now_the_last_member_before_the_closing_brace() {
        let g = Grammar::from_rules([p("a", TerminalLiteral("'x'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.trim_end().ends_with("    }\n}"), "got: {out:?}");
    }

    #[test]
    fn visit_method_leaf_kind_defaults_to_default_result() {
        let g = Grammar::from_rules([p("num", TerminalLiteral("'0'".into()))]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains(
            "fn visit_num(&mut self, node: Node<'tree>) -> Result<Self::Output, Self::Error> {"
        ));
        assert!(out.contains("let _ = node;\n        self.default_result()"));
        assert!(out.contains(
            "**Leaf node**: no visible children; defaults to [`Visitor::default_result`]."
        ));
    }

    #[test]
    fn visit_method_non_leaf_kind_defaults_to_children_visitor() {
        // `num` (a leaf) comes right after `expr` (not a leaf), separated
        // by a blank line — bound the slice there. `num`'s *doc comment*
        // precedes its `fn visit_num(` line, so bounding at that line
        // instead would still leak "Leaf node" into the preceding slice.
        let g = Grammar::from_rules([
            p("expr", nt("num")),
            p("num", TerminalLiteral("'0'".into())),
        ]);
        let out = rv(&g, "g").to_string();
        let expr_method = out
            .split("fn visit_expr(")
            .nth(1)
            .and_then(|s| s.split("\n\n").next())
            .expect("visit_expr method present, followed by a blank line");
        assert!(expr_method.contains("self.children_visitor(node)"));
        assert!(!expr_method.contains("Leaf node"));
    }

    #[test]
    fn visit_method_documents_fields_with_target_kind_and_call() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Sequence(vec![
                    Field("target".into(), Box::new(nt("ident"))),
                    Field("value".into(), Box::new(nt("expr"))),
                ]),
            ),
            p("ident", TerminalLiteral("'i'".into())),
            p("expr", TerminalLiteral("'e'".into())),
        ]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("**Fields:**"));
        assert!(out.contains(
            "- `target` -> `ident` ([`Visitor::visit_ident`]), via `self.field_visitor(node, \"target\")`"
        ));
        assert!(out.contains(
            "- `value` -> `expr` ([`Visitor::visit_expr`]), via `self.field_visitor(node, \"value\")`"
        ));
    }

    #[test]
    fn visit_method_documents_multi_kind_field_union() {
        let g = Grammar::from_rules([
            p(
                "decl",
                Field("value".into(), Box::new(Choice(vec![nt("num"), nt("str")]))),
            ),
            p("num", TerminalLiteral("'0'".into())),
            p("str", TerminalLiteral("'\"\"'".into())),
        ]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains(
            "- `value` -> `num` ([`Visitor::visit_num`]) | `str` ([`Visitor::visit_str`]), via `self.field_visitor(node, \"value\")`"
        ));
    }

    #[test]
    fn visit_method_documents_anonymous_children() {
        let g = Grammar::from_rules([p(
            "decl",
            Sequence(vec![
                TerminalLiteral("'('".into()),
                TerminalLiteral("')'".into()),
            ]),
        )]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("**Anonymous children** (not visited by default): `'('`, `')'`"));
    }

    #[test]
    fn visit_method_no_fields_or_anonymous_children_omits_those_sections() {
        // A doc comment with just the one summary line, immediately
        // followed by the signature — no "**Fields:**" or "**Anonymous
        // children**" section when there's nothing to report.
        let g = Grammar::from_rules([
            p("expr", nt("num")),
            p("num", TerminalLiteral("'0'".into())),
        ]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("    /// Visits a `expr` node.\n    fn visit_expr("));
    }

    #[test]
    fn visit_method_alias_target_kind_is_documented_from_its_aliased_body() {
        let g = Grammar::from_rules([p(
            "expr",
            Alias(
                Box::new(TerminalLiteral("'x'".into())),
                Box::new(nt("renamed")),
            ),
        )]);
        let out = rv(&g, "g").to_string();
        assert!(out.contains("fn visit_renamed(&mut self, node: Node<'tree>)"));
        assert!(out.contains("**Leaf node**"));
    }
}
